### ISSUE TITLE
unexpected error when requesting NAS credentials

### ISSUE THREAD

**Issue by DougAtIBM** [softlayer/softlayer-python#1010]
**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**

### Expected Behavior
a response with credentials

### Actual Behavior
slcli nas credentials 39900373
An unexpected error has occured:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/SoftLayer/CLI/core.py", line 176, in main
    cli.main(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/SoftLayer/CLI/nas/credentials.py", line 21, in cli
    result['password']])
KeyError: 'password'

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues
The following snippet should be able to reproduce the error

### Environment Information
Operating System:
softlayer-python version (`slcli --version`):
slcli (SoftLayer Command-line), version 5.4.4

**Comment by allmightyspiff** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [unexpected error when requesting NAS credentials #1010](https://trello.com/c/mdxmuOI2/23-unexpected-error-when-requesting-nas-credentials-1010)

**Comment by allmightyspiff** [comment]
This will be fixed in the next release, likely sometime next week.
