### ISSUE TITLE
TypeError: cli() got an unexpected keyword argument 'v4' when run "slcli subnet list"

### ISSUE THREAD

**Issue by yingjunyj** [softlayer/softlayer-python#1060]
**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**

### Expected Behavior
# after run "slcli subnet list", I expect it spits out the subnet list. "slcli vlan list", "slcli vs list" all work as expected, only "slcli subnet list" has issue. 

### Actual Behavior
# slcli subnet list
An unexpected error has occured:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/SoftLayer/CLI/core.py", line 182, in main
    cli.main(**kwargs)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
TypeError: cli() got an unexpected keyword argument 'v4'

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues
The following snippet should be able to reproduce the error

### Environment Information
Operating System:
softlayer-python version (`slcli --version`):
# slcli --version
slcli (SoftLayer Command-line), version 5.6.0

**Comment by allmightyspiff** [comment]
This is fixed in master now, and will be included in 5.6.4.
