### ISSUE TITLE
Unexpected keyword argument 'v4' when trying to list subnets with SLCLI

### ISSUE THREAD

**Issue by acamacho82** [softlayer/softlayer-python#1061]
Subnets are not listed when calling to `slcli subnet list`, this happens in the latest version 5.6.0

### Actual Behavior

```
$ slcli subnet list
An unexpected error has occured:
Traceback (most recent call last):
  File "/home/acamacho/.local/lib/python2.7/site-packages/SoftLayer/CLI/core.py", line 182, in main
    cli.main(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
TypeError: cli() got an unexpected keyword argument 'v4'

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues
The following snippet should be able to reproduce the error

```

### Environment Information
Operating System: Linux
softlayer-python version (`slcli --version`): 5.6.0

**Comment by acamacho82** [comment]
dup of #1060
