### ISSUE TITLE
verify_order Fail in API version 5.6.0

### ISSUE THREAD

**Issue by nicebones** [softlayer/softlayer-python#1067]
Try to verify an Order with "verify_order"

CODE:

client = SoftLayer.Client(username='xxxxxxxx', api_key='xxxxxxxxxx',timeout=600)
order_mgr = SoftLayer.OrderingManager(client)
order_mgr.verify_order('DUAL_INTEL_XEON_PROCESSOR_SCALABLE_FAMILY_4_DRIVES',
	'ams03',
	['INTEL_INTEL_XEON_4110_2_10',
 	'OS_VMWARE_SERVER_VIRTUALIZATION_6_5',
 	'RAM_128_GB_DDR4_2133_ECC_REG',
 	'DISK_CONTROLLER_RAID_1',
 	'HARD_DRIVE_1_00_TB_SATA_2',
 	'HARD_DRIVE_1_00_TB_SATA_2',
 	'BANDWIDTH_0_GB',
 	'10_GBPS_DUAL_PRIVATE_NETWORK_UPLINKS_UNBONDED',
 	'REBOOT_KVM_OVER_IP',
 	'1_IP_ADDRESS',
 	'NESSUS_VULNERABILITY_ASSESSMENT_REPORTING',
 	'MONITORING_HOST_PING',
 	'NOTIFICATION_EMAIL_AND_TICKET',
 	'AUTOMATED_NOTIFICATION',
 	'UNLIMITED_SSL_VPN_USERS_1_PPTP_VPN_USER_PER_ACCOUNT'],
	hourly=False,
	complex_type='SoftLayer_Container_Product_Order_Hardware_Server',
	extras={'hardware': [{'domain': 'test.test.loc', 'hostname': 'HostTest'}]}
)

### Expected Behavior
Working in version 5.5.3 (tested)

### Actual Behavior
Calling to SoftLayer.OrderingManager, verify_order faill.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 20, in VerifyOrder
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\SoftLayer\managers\ordering.py", line 443, in verify_order
    extras=extras, quantity=quantity)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\SoftLayer\managers\ordering.py", line 563, in generate_order
    price_ids = self.get_price_id_list(package_keyname, item_keynames, preset_core)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\SoftLayer\managers\ordering.py", line 360, in get_price_id_list
    price_id = self.get_item_price_id(core, matching_item['prices'])
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\SoftLayer\managers\ordering.py", line 383, in get_item_price_id
    elif capacity_min <= int(core) <= capacity_max:
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

This is Working in version 5.5.3 (tested)

### Environment Information
Operating System:
Microsoft Windows [Version 10.0.17134.345]
softlayer-python version (`slcli --version`):
slcli (SoftLayer Command-line), version 5.6.0

**Comment by allmightyspiff** [comment]
Fixed in 5.6.3
