### ISSUE TITLE
Unexpected Error occured when writing SL settings to "/home/vagrant/.softlayer"

### ISSUE THREAD

**Issue by HariPalleti** [softlayer/softlayer-python#1074]
Here is the Error:

### Environment Information
Operating System:
softlayer-python version (`slcli --version`):

**Comment by HariPalleti** [comment]
Here is the Error:
Are you sure you want to write settings to "/home/vagrant/.softlayer"? [Y/n]: Y
Configuration Updated Successfully
An unexpected error has occured:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/SoftLayer/CLI/core.py", line 163, in main
    cli.main(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1102, in _process_result
    **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
TypeError: output_diagnostics() got multiple values for keyword argument 'verbose'

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues

Environment Information
Operating System: Linux vagrant-ubuntu-trusty-64 3.13.0-112-generic #159-Ubuntu SMP Fri Mar 3 15:26:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
softlayer-python version (slcli --version):slcli (SoftLayer Command-line), version 5.2.1

**Comment by allmightyspiff** [comment]
After looking at this a bit, it seem you will get this error if you have an existing ~/.softlayer file with the REST endpoint as the url.

Also, using the REST endpoint as input to `slcli config setup` will not work properly and generate a 401 unauthorized error.


As a quick fix, just remove the ~/.softlayer file before running `slcli config setup`. 

Still working on a code fix for this problem.
