### ISSUE TITLE
Unexpected error after slcli config setup

### ISSUE THREAD

**Issue by HariPalleti** [softlayer/softlayer-python#1082]
Getting an Error while running slcli config setup
Here is the complete trace of the error:
An unexpected error has occured:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/SoftLayer/CLI/core.py", line 163, in main
    cli.main(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/SoftLayer/CLI/config/setup.py", line 62, in cli
    'timeout': timeout})))
  File "/usr/local/lib/python2.7/dist-packages/SoftLayer/CLI/environment.py", line 51, in fmt
    return formatting.format_output(output, fmt=self.format)
  File "/usr/local/lib/python2.7/dist-packages/SoftLayer/CLI/formatting.py", line 38, in format_output
    return str(format_prettytable(data))
  File "/usr/local/lib/python2.7/dist-packages/SoftLayer/CLI/formatting.py", line 83, in format_prettytable
    ptable.hrules = prettytable.FRAME
AttributeError: 'module' object has no attribute 'FRAME'

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues

slcli (SoftLayer Command-line), version 5.2.1
Python 2.7.6
Linux vagrant-ubuntu-trusty-64 3.13.0-112-generic #159-Ubuntu SMP Fri Mar 3 15:26:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by allmightyspiff** [comment]
Try updating to the latest version (5.6.4), which should hopefully fix this error.

**Comment by HariPalleti** [comment]
Thanks @allmightyspiff it worked!!

**Comment by allmightyspiff** [comment]
👍
