### ISSUE TITLE
Unable to request new subnet: cli() got an unexpected keyword argument 'v6'

### ISSUE THREAD

**Issue by jtapsl** [softlayer/softlayer-python#1129]
slcli subnet create private 64 $MYVLANID
and
slcli subnet create private 64 $MYVLANID --test
both fail.

### Expected Behavior
Subnet is requested.

### Actual Behavior
$ slcli subnet create private 64 $MYVLANID 
An unexpected error has occured:
Traceback (most recent call last):
  File "/home/user/.local/lib/python2.7/site-packages/SoftLayer/CLI/core.py", line 182, in main
    cli.main(**kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
TypeError: cli() got an unexpected keyword argument 'v6'

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues

### Environment Information
Operating System: RHEL 7.6
softlayer-python version (`slcli --version`): slcli (SoftLayer Command-line), version 5.7.1

**Comment by allmightyspiff** [comment]
related to #1060, well look into it.
