### ISSUE TITLE
TestHelpSetup.test_setup_cancel isn't working as expected

### ISSUE THREAD

**Issue by allmightyspiff** [softlayer/softlayer-python#1131]
Related to #1095

This test (at least on OpenSuse/RHEL) isn't canceling properly and trying to make an API call.
```
[  227s] =================================== FAILURES ===================================
[  227s] _______________________ TestHelpSetup.test_setup_cancel ________________________
[  227s] NOTE: Incompatible Exception Representation, displaying natively:
[  227s] 
[  227s] _StringException: Traceback (most recent call last):
[  227s]   File "/usr/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
[  227s]     return func(*args, **keywargs)
[  227s]   File "/home/abuild/rpmbuild/BUILD/softlayer-python-5.7.1/tests/CLI/modules/config_tests.py", line 90, in test_setup_cancel
[  227s]     self.assertEqual(result.exit_code, 2)
[  227s]   File "/usr/lib/python2.7/site-packages/testtools/testcase.py", line 411, in assertEqual
[  227s]     self.assertThat(observed, matcher, message)
[  227s]   File "/usr/lib/python2.7/site-packages/testtools/testcase.py", line 498, in assertThat
[  227s]     raise mismatch_error
[  227s] testtools.matchers._impl.MismatchError: 1 != 2
[  227s] 
[  227s] 

[  227s] ----------------------------- Captured stderr call -----------------------------
[  227s] WARNING:urllib3.connectionpool:Retrying (Retry(total=9, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f9afe8ede10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /xmlrpc/v3.1/SoftLayer_Account
[  227s] WARNING:urllib3.connectionpool:Retrying (Retry(total=8, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f9afea61210>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /xmlrpc/v3.1/SoftLayer_Account
[  227s] WARNING:urllib3.connectionpool:Retrying (Retry(total=7, connect=0, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f9afea61a10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /xmlrpc/v3.1/SoftLayer_Account
[  227s] ------------------------------ Captured log call -------------------------------
[  227s] connectionpool.py          662 WARNING  Retrying (Retry(total=9, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f9afe8ede10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /xmlrpc/v3.1/SoftLayer_Account
[  227s] connectionpool.py          662 WARNING  Retrying (Retry(total=8, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f9afea61210>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /xmlrpc/v3.1/SoftLayer_Account
[  227s] connectionpool.py          662 WARNING  Retrying (Retry(total=7, connect=0, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f9afea61a10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /xmlrpc/v3.1/SoftLayer_Account
[  227s] ============== 1 failed, 1296 passed, 4 skipped in 75.02 seconds ===============
```

**Comment by allmightyspiff** [comment]
This error is reproducible by adding `127.0.0.1 api.softlayer.com` to `/etc/hosts`

**Comment by pgajdos** [comment]
Thank you very much.

Confirmed this is fixed by commit above.
