### ISSUE TITLE
error in slcli hw detail

### ISSUE THREAD

**Issue by scottwn** [softlayer/softlayer-python#1192]
**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**

### Expected Behavior
slcli hw detail should display details of a bare metal when I supply an ID

### Actual Behavior
```
scottwn@MacBook-Pro ~/qiskit-terra> slcli hw detail 1326127
An unexpected error has occured:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/SoftLayer/CLI/core.py", line 182, in main
    cli.main(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/SoftLayer/CLI/hardware/detail.py", line 60, in cli
    bandwidth = hardware.get_bandwidth_allocation(hardware_id)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/SoftLayer/managers/hardware.py", line 701, in get_bandwidth_allocation
    return {'allotment': allotment.get('allocation'), 'useage': useage}
AttributeError: 'str' object has no attribute 'get'

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues
The following snippet should be able to reproduce the error
```

### Environment Information
Operating System: macOS 10.14.6
softlayer-python version (`slcli --version`): 5.8.0

**Comment by scottwn** [comment]
Upgraded to 5.8.2 and see the same error

**Comment by cletomartin** [comment]
Just seen in a new provisioned nodes so possibly it is related with new nodes? 

Quick workaround:

```python
return {'allotment': (allotment or {}).get('allocation'), 'useage': useage}
```
The right solution will come after understanding why `self.client.call` return `''` for `allotment`.

**Comment by allmightyspiff** [comment]
> The right solution will come after understanding why self.client.call return '' for allotment.

The API does this when a relational property doesn't have any values. So in this case the hardware in question doesn't have a bandwidth allotment.  Now, I'm not sure if every server is supposed to always have an allotment, but its certainly something we can work around with in the CLI.
