### ISSUE TITLE
Ticket upload doesn't work in REST

### ISSUE THREAD

**Issue by allmightyspiff** [softlayer/softlayer-python#1266]
```
$ slcli ticket upload --path ./out.txt --name out.txt  108158052
An unexpected error has occured:
Traceback (most recent call last):
  File "c:\users\allmi\source\py37\lib\site-packages\SoftLayer\CLI\core.py", line 207, in main
    cli.main(**kwargs)
  File "c:\users\allmi\source\py37\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\allmi\source\py37\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\allmi\source\py37\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\allmi\source\py37\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\allmi\source\py37\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\allmi\source\py37\lib\site-packages\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "c:\users\allmi\source\py37\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\allmi\source\py37\lib\site-packages\SoftLayer\CLI\ticket\upload.py", line 36, in cli
    file_name=name)
  File "c:\users\allmi\source\py37\lib\site-packages\SoftLayer\managers\ticket.py", line 104, in upload_attachment
    return self.ticket.addAttachedFile(file_object, id=ticket_id)
  File "c:\users\allmi\source\py37\lib\site-packages\SoftLayer\API.py", line 388, in call_handler
    return self(name, *args, **kwargs)
  File "c:\users\allmi\source\py37\lib\site-packages\SoftLayer\API.py", line 356, in call
    return self.client.call(self.name, name, *args, **kwargs)
  File "c:\users\allmi\source\py37\lib\site-packages\SoftLayer\API.py", line 264, in call
    return self.transport(request)
  File "c:\users\allmi\source\py37\lib\site-packages\SoftLayer\transports.py", line 461, in __call__
    call.result = self.transport(call)
  File "c:\users\allmi\source\py37\lib\site-packages\SoftLayer\transports.py", line 362, in __call__
    request.payload = json.dumps(body)
  File "C:\Users\allmi\AppData\Local\Programs\Python\Python37\Lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\allmi\AppData\Local\Programs\Python\Python37\Lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\allmi\AppData\Local\Programs\Python\Python37\Lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\allmi\AppData\Local\Programs\Python\Python37\Lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues
The following snippet should be able to reproduce the error
```

**Comment by allmightyspiff** [comment]
Looks like the xmlrpc client auto base64 encodes binary/bytes data, which i think the REST client might need to do as well
