### ISSUE TITLE
Error in subnet listing

### ISSUE THREAD

**Issue by LOTRg** [softlayer/softlayer-python#1390]
> Reminder: No username or APIkeys should be added to these issues, as they are public.

**Describe the bug**
when listing subnets it fails with error. command used `slcli subnet list`

**Error Output**
Calling: SoftLayer_Account::getSubnets(id=None, mask='hardware,datacenter,ipAddressCount,virtualGuests,id,networkIdentifier,cidr,subnetType,gateway,broadcastAddress,usableIpAddressCount,note,tagReferences[tag],networkVlan[id,networkSpace]', filter='{'subnets': {'subnetType': {'operation': '!= GLOBAL_IP'}}}', args=(), limit=100, offset=0))
An unexpected error has occured:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/SoftLayer/CLI/core.py", line 209, in main
    cli.main(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/SoftLayer/CLI/subnet/list.py", line 66, in cli
    subnet['networkVlanId'],
KeyError: 'networkVlanId'

**Expected behavior**
Expecting the list of subnets to show.

**Screenshots**
Screenshot attached.
![Selection_005](https://user-images.githubusercontent.com/16282038/100984544-ddb44c00-3518-11eb-8725-8fd6df3ca935.png)

**Version**
Include the output of `slcli --version`
Current: slcli (SoftLayer Command-line) v5.9.1
Latest:  slcli (SoftLayer Command-line) v5.9.1

**Comment by allmightyspiff** [comment]
This should be fixed in https://github.com/softlayer/softlayer-python/pull/1379
I'll make a new release today to include the fix, sorry for not pushing it out sooner.

**Comment by allmightyspiff** [comment]
[5.9.2](https://github.com/softlayer/softlayer-python/releases/tag/v5.9.2) is out now, let us know if that doesn't fix the issue though.
