### ISSUE TITLE
Unable to create users:  No valid authentication headers found

### ISSUE THREAD

**Issue by aaronwmorris** [softlayer/softlayer-python#1540]
**Describe the bug**
Creating users via slclient['SoftLayer_User_Customer'].createObject(userinfo, password, password) fails with the exception:

```
Traceback (most recent call last):
  File "/home/magnum/virtualenv/magnum_python3.6/lib/python3.6/site-packages/celery/app/trace.py", line 450, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/magnum/git/magnum/magnum/tasks.py", line 232, in __call__
    return super(MagnumTask, self).__call__(*args, **kwargs)
  File "/home/magnum/virtualenv/magnum_python3.6/lib/python3.6/site-packages/celery/app/trace.py", line 731, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/magnum/git/magnum/magnum/tasks.py", line 9174, in run
    create_user_sldata = slclient['SoftLayer_User_Customer'].createObject(userinfo, password, password)
  File "/home/magnum/virtualenv/magnum_python3.6/lib/python3.6/site-packages/SoftLayer/API.py", line 609, in call_handler
    return self(name, *args, **kwargs)
  File "/home/magnum/virtualenv/magnum_python3.6/lib/python3.6/site-packages/SoftLayer/API.py", line 577, in call
    return self.client.call(self.name, name, *args, **kwargs)
  File "/home/magnum/virtualenv/magnum_python3.6/lib/python3.6/site-packages/SoftLayer/API.py", line 301, in call
    return self.transport(request)
  File "/home/magnum/virtualenv/magnum_python3.6/lib/python3.6/site-packages/SoftLayer/transports.py", line 248, in __call__
    raise _ex(ex.faultCode, ex.faultString) from ex
SoftLayer.exceptions.SoftLayerAPIError: SoftLayerAPIError(SoftLayer_Exception): No valid authentication headers found.

```

**Version**
SoftLayer==5.9.7

**Comment by aaronwmorris** [comment]
This code has been working for a number of years except I finally got around to migrating my code to Python 3.

I stripped my code down to the bare minimum and I still got the error.  I was about to submit my code so I was sanitizing the user details and then the user creation started working.

It appears the problem might be a character encoding issue.  The user's name included a character with an accent mark and that appears to be causing the error regarding the headers.

The "displayName" attribute has a character with an accent mark.

```
#!/usr/bin/env python3

import SoftLayer
import sys
import getpass


apiuser = input('API User: ')
apikey = getpass.getpass(prompt='API Key: ')


username = 'testuser.1810963.3'
user_pass = 'TypIcyfavCier@5'
vpn_pass = 'TypIcyfavCier@5'


slclient = SoftLayer.Client(
    username=apiuser,
    api_key=apikey,
    timeout=120,
)

user_data = {
    'address1': '1 New Orchard Road',
    'city': 'Armonk',
    'companyName': 'IBM',
    'country': 'US',
    'denyAllResourceAccessOnCreateFlag': False,
    'displayName': 'First é Last',
    #'displayName': 'First Last',
    'email': 'redacted3@ibm.com',
    'firstName': 'First',
    'hasFullDedicatedHostAccessFlag': True,
    'hasFullHardwareAccessFlag': True,
    'hasFullVirtualGuestAccessFlag': True,
    'lastName': 'Last',
    'postalCode': '10504',
    'pptpVpnAllowedFlag': False,
    'secondaryLoginManagementFlag': False,
    'secondaryLoginRequiredFlag': True,
    'secondaryPasswordTimeoutDays': 90,
    'sslVpnAllowedFlag': False,
    'state': 'NY',
    'timezoneId': 117,
    'userStatusId': 1001,
    'username': username,
    'vpnManualConfig': False,
}

slclient['SoftLayer_User_Customer'].createObject(user_data, user_pass, vpn_pass)
```


Results in the following exception
```
$ ./test_user_create.py
API User: IBM1810963
API Key:
Traceback (most recent call last):
  File "/home/magnum/virtualenv/magnum_python3.6/lib/python3.6/site-packages/SoftLayer/transports.py", line 226, in __call__
    result = xmlrpc.client.loads(resp.content)[0][0]
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/xmlrpc/client.py", line 1021, in loads
    return u.close(), u.getmethodname()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/xmlrpc/client.py", line 656, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault SoftLayer_Exception: 'No valid authentication headers found.'>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./test_user_create.py", line 50, in <module>
    slclient['SoftLayer_User_Customer'].createObject(user_data, user_pass, vpn_pass)
  File "/home/magnum/virtualenv/magnum_python3.6/lib/python3.6/site-packages/SoftLayer/API.py", line 609, in call_handler
    return self(name, *args, **kwargs)
  File "/home/magnum/virtualenv/magnum_python3.6/lib/python3.6/site-packages/SoftLayer/API.py", line 577, in call
    return self.client.call(self.name, name, *args, **kwargs)
  File "/home/magnum/virtualenv/magnum_python3.6/lib/python3.6/site-packages/SoftLayer/API.py", line 301, in call
    return self.transport(request)
  File "/home/magnum/virtualenv/magnum_python3.6/lib/python3.6/site-packages/SoftLayer/transports.py", line 248, in __call__
    raise _ex(ex.faultCode, ex.faultString) from ex
SoftLayer.exceptions.SoftLayerAPIError: SoftLayerAPIError(SoftLayer_Exception): No valid authentication headers found.
```

**Comment by allmightyspiff** [comment]
@aaronwmorris Thanks for that, I can now reproduce this issue. It seems you are right that non-ascii characters are causing problems with the XML-RPC transport somehow. I'll look into fixing that.

In the mean time, it looks like this request should work fine with the REST endpoint `endpoint_url = https://api.softlayer.com/rest/v3.1` so you might want to try that until I figure out how to resolve this issue.
