### ISSUE TITLE
slcli error: 'CommandLoader' object has no attribute 'resultcallback'

### ISSUE THREAD

**Issue by hasan4791** [softlayer/softlayer-python#1601]
slcli throws error in python 3.8 & python3.9, its running on the container image redhat-ubi8.5.
Tried testing the same with python3.6 which works fine. (logs are attached)
```
root@create-cluster-testing ]# python3
Python 3.8.8 (default, Aug 11 2021, 06:52:42) 
[GCC 8.5.0 20210514 (Red Hat 8.5.0-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
[root@create-cluster-testing ]# 
[root@create-cluster-testing ]# slcli
bash: slcli: command not found
[root@create-cluster-testing ]# 
[root@create-cluster-testing ]# 
[root@create-cluster-testing ]# pip3 install softlayer
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting softlayer
  Downloading https://files.pythonhosted.org/packages/ea/58/fd476cc96c19fa980ef7c1d5aaa31a35dd396f97aed34040f3cf9e5c2a5a/SoftLayer-6.0.1-py2.py3-none-any.whl (652kB)
     |████████████████████████████████| 655kB 16.9MB/s 
Collecting requests>=2.20.0
  Downloading https://files.pythonhosted.org/packages/2d/61/08076519c80041bc0ffa1a8af0cbd3bf3e2b62af10435d269a9d0f40564d/requests-2.27.1-py2.py3-none-any.whl (63kB)
     |████████████████████████████████| 71kB 15.9MB/s 
Collecting prompt-toolkit>=2
  Downloading https://files.pythonhosted.org/packages/00/e4/beb2fad0bec554a011b321d0f6b99981f9171c0b05d03a6948e45ac8a5be/prompt_toolkit-3.0.28-py3-none-any.whl (380kB)
     |████████████████████████████████| 389kB 50.7MB/s 
Collecting click>=7
  Downloading https://files.pythonhosted.org/packages/86/3e/3a523bdd24510288b1b850428e01172116a29268378b1da9a8d0b894a115/click-8.1.0-py3-none-any.whl (96kB)
     |████████████████████████████████| 102kB 16.9MB/s 
Collecting pygments>=2.0.0
  Downloading https://files.pythonhosted.org/packages/1d/17/ed4d2df187995561b28f1073df24137cb750e12f9879d291cc8ab67c65d2/Pygments-2.11.2-py3-none-any.whl (1.1MB)
     |████████████████████████████████| 1.1MB 50.3MB/s 
Collecting urllib3>=1.24
  Downloading https://files.pythonhosted.org/packages/ec/03/062e6444ce4baf1eac17a6a0ebfe36bb1ad05e1df0e20b110de59c278498/urllib3-1.26.9-py2.py3-none-any.whl (138kB)
     |████████████████████████████████| 143kB 57.8MB/s 
Collecting prettytable>=2.0.0
  Downloading https://files.pythonhosted.org/packages/96/53/91638391af5a68d27402b920ccc3fdfae51dd3e333476b414393d4478a70/prettytable-3.2.0-py3-none-any.whl
Collecting idna<4,>=2.5; python_version >= "3"
  Downloading https://files.pythonhosted.org/packages/04/a2/d918dcd22354d8958fe113e1a3630137e0fc8b44859ade3063982eacd2a4/idna-3.3-py3-none-any.whl (61kB)
     |████████████████████████████████| 61kB 17.6MB/s 
Collecting charset-normalizer~=2.0.0; python_version >= "3"
  Downloading https://files.pythonhosted.org/packages/06/b3/24afc8868eba069a7f03650ac750a778862dc34941a4bebeb58706715726/charset_normalizer-2.0.12-py3-none-any.whl
Collecting certifi>=2017.4.17
  Downloading https://files.pythonhosted.org/packages/37/45/946c02767aabb873146011e665728b680884cd8fe70dde973c640e45b775/certifi-2021.10.8-py2.py3-none-any.whl (149kB)
     |████████████████████████████████| 153kB 36.6MB/s 
Collecting wcwidth
  Downloading https://files.pythonhosted.org/packages/59/7c/e39aca596badaf1b78e8f547c807b04dae603a433d3e7a7e04d67f2ef3e5/wcwidth-0.2.5-py2.py3-none-any.whl
Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests, wcwidth, prompt-toolkit, click, pygments, prettytable, softlayer
Successfully installed certifi-2021.10.8 charset-normalizer-2.0.12 click-8.1.0 idna-3.3 prettytable-3.2.0 prompt-toolkit-3.0.28 pygments-2.11.2 requests-2.27.1 softlayer-6.0.1 urllib3-1.26.9 wcwidth-0.2.5
[root@create-cluster-testing ]# 
[root@create-cluster-testing ]# 
[root@create-cluster-testing ]# 
[root@create-cluster-testing ]# slcli 
Traceback (most recent call last):
  File "/usr/local/bin/slcli", line 5, in <module>
    from SoftLayer.CLI.core import main
  File "/usr/local/lib64/python3.8/site-packages/SoftLayer/CLI/core.py", line 165, in <module>
    @cli.resultcallback()
AttributeError: 'CommandLoader' object has no attribute 'resultcallback'
[root@create-cluster-testing ]#

```

[slcli-python36.txt](https://github.com/softlayer/softlayer-python/files/8378015/slcli-python36.txt)

**Comment by hasan4791** [comment]
Attach logs from the RHEL8.5 VM created on IBMCloud classic aswell
```
[root@rhel8-latest-bootstrap ~]# yum install python38
Updating Subscription Management repositories.
Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)                                                                                            39 kB/s | 2.4 kB     00:00    
Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)                                                                                         42 kB/s | 2.8 kB     00:00    
Dependencies resolved.
================================================================================================================================================================================
 Package                                   Architecture           Version                                                Repository                                        Size
================================================================================================================================================================================
Installing:
 python38                                  x86_64                 3.8.8-4.module+el8.5.0+12205+a865257a                  rhel-8-for-x86_64-appstream-rpms                  79 k
Installing dependencies:
 python38-libs                             x86_64                 3.8.8-4.module+el8.5.0+12205+a865257a                  rhel-8-for-x86_64-appstream-rpms                 8.3 M
 python38-pip-wheel                        noarch                 19.3.1-4.module+el8.5.0+12205+a865257a                 rhel-8-for-x86_64-appstream-rpms                 1.2 M
 python38-setuptools-wheel                 noarch                 41.6.0-5.module+el8.5.0+12205+a865257a                 rhel-8-for-x86_64-appstream-rpms                 304 k
Installing weak dependencies:
 python38-pip                              noarch                 19.3.1-4.module+el8.5.0+12205+a865257a                 rhel-8-for-x86_64-appstream-rpms                 1.9 M
 python38-setuptools                       noarch                 41.6.0-5.module+el8.5.0+12205+a865257a                 rhel-8-for-x86_64-appstream-rpms                 668 k
Enabling module streams:
 python38                                                         3.8                                                                                                          

Transaction Summary
================================================================================================================================================================================
Install  6 Packages

Total download size: 12 M
Installed size: 45 M
Is this ok [y/N]: y
Downloading Packages:
(1/6): python38-setuptools-wheel-41.6.0-5.module+el8.5.0+12205+a865257a.noarch.rpm                                                              1.9 MB/s | 304 kB     00:00    
(2/6): python38-pip-wheel-19.3.1-4.module+el8.5.0+12205+a865257a.noarch.rpm                                                                     5.2 MB/s | 1.2 MB     00:00    
(3/6): python38-setuptools-41.6.0-5.module+el8.5.0+12205+a865257a.noarch.rpm                                                                    5.9 MB/s | 668 kB     00:00    
(4/6): python38-3.8.8-4.module+el8.5.0+12205+a865257a.x86_64.rpm                                                                                1.7 MB/s |  79 kB     00:00    
(5/6): python38-pip-19.3.1-4.module+el8.5.0+12205+a865257a.noarch.rpm                                                                            19 MB/s | 1.9 MB     00:00    
(6/6): python38-libs-3.8.8-4.module+el8.5.0+12205+a865257a.x86_64.rpm                                                                            17 MB/s | 8.3 MB     00:00    
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                            25 MB/s |  12 MB     00:00     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                        1/1 
  Installing       : python38-setuptools-wheel-41.6.0-5.module+el8.5.0+12205+a865257a.noarch                                                                                1/6 
  Installing       : python38-pip-wheel-19.3.1-4.module+el8.5.0+12205+a865257a.noarch                                                                                       2/6 
  Installing       : python38-libs-3.8.8-4.module+el8.5.0+12205+a865257a.x86_64                                                                                             3/6 
  Installing       : python38-3.8.8-4.module+el8.5.0+12205+a865257a.x86_64                                                                                                  4/6 
  Running scriptlet: python38-3.8.8-4.module+el8.5.0+12205+a865257a.x86_64                                                                                                  4/6 
  Installing       : python38-setuptools-41.6.0-5.module+el8.5.0+12205+a865257a.noarch                                                                                      5/6 
  Running scriptlet: python38-setuptools-41.6.0-5.module+el8.5.0+12205+a865257a.noarch                                                                                      5/6 
  Installing       : python38-pip-19.3.1-4.module+el8.5.0+12205+a865257a.noarch                                                                                             6/6 
  Running scriptlet: python38-pip-19.3.1-4.module+el8.5.0+12205+a865257a.noarch                                                                                             6/6 
  Verifying        : python38-pip-wheel-19.3.1-4.module+el8.5.0+12205+a865257a.noarch                                                                                       1/6 
  Verifying        : python38-setuptools-wheel-41.6.0-5.module+el8.5.0+12205+a865257a.noarch                                                                                2/6 
  Verifying        : python38-libs-3.8.8-4.module+el8.5.0+12205+a865257a.x86_64                                                                                             3/6 
  Verifying        : python38-setuptools-41.6.0-5.module+el8.5.0+12205+a865257a.noarch                                                                                      4/6 
  Verifying        : python38-3.8.8-4.module+el8.5.0+12205+a865257a.x86_64                                                                                                  5/6 
  Verifying        : python38-pip-19.3.1-4.module+el8.5.0+12205+a865257a.noarch                                                                                             6/6 
Installed products updated.

Installed:
  python38-3.8.8-4.module+el8.5.0+12205+a865257a.x86_64                               python38-libs-3.8.8-4.module+el8.5.0+12205+a865257a.x86_64                               
  python38-pip-19.3.1-4.module+el8.5.0+12205+a865257a.noarch                          python38-pip-wheel-19.3.1-4.module+el8.5.0+12205+a865257a.noarch                         
  python38-setuptools-41.6.0-5.module+el8.5.0+12205+a865257a.noarch                   python38-setuptools-wheel-41.6.0-5.module+el8.5.0+12205+a865257a.noarch                  

Complete!
[root@rhel8-latest-bootstrap ~]# 
[root@rhel8-latest-bootstrap ~]# 
[root@rhel8-latest-bootstrap ~]# 
[root@rhel8-latest-bootstrap ~]# pip3 install softlayer
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting softlayer
  Downloading https://files.pythonhosted.org/packages/ea/58/fd476cc96c19fa980ef7c1d5aaa31a35dd396f97aed34040f3cf9e5c2a5a/SoftLayer-6.0.1-py2.py3-none-any.whl (652kB)
     |████████████████████████████████| 655kB 11.7MB/s 
Collecting urllib3>=1.24
  Downloading https://files.pythonhosted.org/packages/ec/03/062e6444ce4baf1eac17a6a0ebfe36bb1ad05e1df0e20b110de59c278498/urllib3-1.26.9-py2.py3-none-any.whl (138kB)
     |████████████████████████████████| 143kB 28.8MB/s 
Collecting prompt-toolkit>=2
  Downloading https://files.pythonhosted.org/packages/00/e4/beb2fad0bec554a011b321d0f6b99981f9171c0b05d03a6948e45ac8a5be/prompt_toolkit-3.0.28-py3-none-any.whl (380kB)
     |████████████████████████████████| 389kB 29.1MB/s 
Collecting prettytable>=2.0.0
  Downloading https://files.pythonhosted.org/packages/96/53/91638391af5a68d27402b920ccc3fdfae51dd3e333476b414393d4478a70/prettytable-3.2.0-py3-none-any.whl
Collecting requests>=2.20.0
  Downloading https://files.pythonhosted.org/packages/2d/61/08076519c80041bc0ffa1a8af0cbd3bf3e2b62af10435d269a9d0f40564d/requests-2.27.1-py2.py3-none-any.whl (63kB)
     |████████████████████████████████| 71kB 12.3MB/s 
Collecting pygments>=2.0.0
  Downloading https://files.pythonhosted.org/packages/1d/17/ed4d2df187995561b28f1073df24137cb750e12f9879d291cc8ab67c65d2/Pygments-2.11.2-py3-none-any.whl (1.1MB)
     |████████████████████████████████| 1.1MB 28.1MB/s 
Collecting click>=7
  Downloading https://files.pythonhosted.org/packages/86/3e/3a523bdd24510288b1b850428e01172116a29268378b1da9a8d0b894a115/click-8.1.0-py3-none-any.whl (96kB)
     |████████████████████████████████| 102kB 15.2MB/s 
Collecting wcwidth
  Downloading https://files.pythonhosted.org/packages/59/7c/e39aca596badaf1b78e8f547c807b04dae603a433d3e7a7e04d67f2ef3e5/wcwidth-0.2.5-py2.py3-none-any.whl
Collecting certifi>=2017.4.17
  Downloading https://files.pythonhosted.org/packages/37/45/946c02767aabb873146011e665728b680884cd8fe70dde973c640e45b775/certifi-2021.10.8-py2.py3-none-any.whl (149kB)
     |████████████████████████████████| 153kB 29.0MB/s 
Collecting charset-normalizer~=2.0.0; python_version >= "3"
  Downloading https://files.pythonhosted.org/packages/06/b3/24afc8868eba069a7f03650ac750a778862dc34941a4bebeb58706715726/charset_normalizer-2.0.12-py3-none-any.whl
Collecting idna<4,>=2.5; python_version >= "3"
  Downloading https://files.pythonhosted.org/packages/04/a2/d918dcd22354d8958fe113e1a3630137e0fc8b44859ade3063982eacd2a4/idna-3.3-py3-none-any.whl (61kB)
     |████████████████████████████████| 61kB 11.2MB/s 
Installing collected packages: urllib3, wcwidth, prompt-toolkit, prettytable, certifi, charset-normalizer, idna, requests, pygments, click, softlayer
Successfully installed certifi-2021.10.8 charset-normalizer-2.0.12 click-8.1.0 idna-3.3 prettytable-3.2.0 prompt-toolkit-3.0.28 pygments-2.11.2 requests-2.27.1 softlayer-6.0.1 urllib3-1.26.9 wcwidth-0.2.5
[root@rhel8-latest-bootstrap ~]# 
[root@rhel8-latest-bootstrap ~]# slcli 
Traceback (most recent call last):
  File "/usr/local/bin/slcli", line 5, in <module>
    from SoftLayer.CLI.core import main
  File "/usr/local/lib64/python3.8/site-packages/SoftLayer/CLI/core.py", line 165, in <module>
    @cli.resultcallback()
AttributeError: 'CommandLoader' object has no attribute 'resultcallback'
[root@rhel8-latest-bootstrap ~]# 
[root@rhel8-latest-bootstrap ~]# 
[root@rhel8-latest-bootstrap ~]# uname -r
4.18.0-348.12.2.el8_5.x86_64
[root@rhel8-latest-bootstrap ~]# 
[root@rhel8-latest-bootstrap ~]# cat /etc/os-release 
NAME="Red Hat Enterprise Linux"
VERSION="8.5 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.5 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.5
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.5"
[root@rhel8-latest-bootstrap ~]# 

```

**Comment by allmightyspiff** [comment]
@hasan4791 Try with version 6.0.2 now.  The problem was with the `click 8.1.0` library, so I've pinned softlayer-python to `click 8.0.4` for now.
