### ISSUE TITLE
unexpected error when using vlan list with --limit 0 or 999 and a large number of vlans (>400)

### ISSUE THREAD

**Issue by YuriG7** [softlayer/softlayer-python#1844]
**Describe the bug**

When I try to retrieve a large number of vlans (more than 400) the CLI returns an unexpected error. Here is the output of the command:

```
$ slcli -v vlan list --limit 0
Calling: SoftLayer_Account::getNetworkVlans(id=None, mask='firewallInterfaces,hardwareCount,primaryRouter[id, fullyQualifiedDomainName, datacenter],subnetCount,billingItem,totalPrimaryIpAddressCount,virtualGuestCount,networkSpace,networkVlanFirewall[id,fullyQualifiedDomainName,primaryIpAddress],attachedNetworkGateway[id,name,networkFirewall],tagReferences[tag[name]]', filter='{'networkVlans': {'id': {'operation': 'orderBy', 'options': [{'name': 'sort', 'value': ['ASC']}]}}}', args=(), limit=100, offset=0))
Calling: SoftLayer_Account::getNetworkVlans(id=None, mask='firewallInterfaces,hardwareCount,primaryRouter[id, fullyQualifiedDomainName, datacenter],subnetCount,billingItem,totalPrimaryIpAddressCount,virtualGuestCount,networkSpace,networkVlanFirewall[id,fullyQualifiedDomainName,primaryIpAddress],attachedNetworkGateway[id,name,networkFirewall],tagReferences[tag[name]]', filter='{'networkVlans': {'id': {'operation': 'orderBy', 'options': [{'name': 'sort', 'value': ['ASC']}]}}}', args=(), limit=100, offset=100))
Calling: SoftLayer_Account::getNetworkVlans(id=None, mask='firewallInterfaces,hardwareCount,primaryRouter[id, fullyQualifiedDomainName, datacenter],subnetCount,billingItem,totalPrimaryIpAddressCount,virtualGuestCount,networkSpace,networkVlanFirewall[id,fullyQualifiedDomainName,primaryIpAddress],attachedNetworkGateway[id,name,networkFirewall],tagReferences[tag[name]]', filter='{'networkVlans': {'id': {'operation': 'orderBy', 'options': [{'name': 'sort', 'value': ['ASC']}]}}}', args=(), limit=100, offset=200))
Calling: SoftLayer_Account::getNetworkVlans(id=None, mask='firewallInterfaces,hardwareCount,primaryRouter[id, fullyQualifiedDomainName, datacenter],subnetCount,billingItem,totalPrimaryIpAddressCount,virtualGuestCount,networkSpace,networkVlanFirewall[id,fullyQualifiedDomainName,primaryIpAddress],attachedNetworkGateway[id,name,networkFirewall],tagReferences[tag[name]]', filter='{'networkVlans': {'id': {'operation': 'orderBy', 'options': [{'name': 'sort', 'value': ['ASC']}]}}}', args=(), limit=100, offset=300))
Calling: SoftLayer_Account::getNetworkVlans(id=None, mask='firewallInterfaces,hardwareCount,primaryRouter[id, fullyQualifiedDomainName, datacenter],subnetCount,billingItem,totalPrimaryIpAddressCount,virtualGuestCount,networkSpace,networkVlanFirewall[id,fullyQualifiedDomainName,primaryIpAddress],attachedNetworkGateway[id,name,networkFirewall],tagReferences[tag[name]]', filter='{'networkVlans': {'id': {'operation': 'orderBy', 'options': [{'name': 'sort', 'value': ['ASC']}]}}}', args=(), limit=100, offset=400))
Calling: SoftLayer_Network_Pod::getAllObjects(id=None, mask='mask[name, datacenterLongName, frontendRouterId, capabilities, datacenterId, backendRouterId, backendRouterName, frontendRouterName]', filter='{'name': {'operation': 'orderBy', 'options': [{'name': 'sort', 'value': ['DESC']}]}}', args=(), limit=None, offset=None))
An unexpected error has occured:
Traceback (most recent call last):
  File "/home/yurig/.local/lib/python3.6/site-packages/SoftLayer/CLI/core.py", line 182, in main
    cli.main(**kwargs)
  File "/home/yurig/.local/lib/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/yurig/.local/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/yurig/.local/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/yurig/.local/lib/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yurig/.local/lib/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/yurig/.local/lib/python3.6/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/yurig/.local/lib/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/yurig/.local/lib/python3.6/site-packages/SoftLayer/CLI/vlan/list.py", line 68, in cli
    vlan.get('networkSpace').capitalize(),
AttributeError: 'NoneType' object has no attribute 'capitalize'

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues
The following snippet should be able to reproduce the error
```

**Expected behavior**
I expect the CLI to return a list of all VLANs as it used to work in older version (e.g. v5.9.2).

**Screenshots**
N/A

**Version**
```
$ slcli --version
Current: slcli (SoftLayer Command-line) v6.1.2
Latest:  slcli (SoftLayer Command-line) v6.1.3
```

But the same issues occurs in `v6.1.3` as well.

**Comment by allmightyspiff** [comment]
It looks like one of your Vlans might not have a `networkSpace` attribute... which is odd.  

The following command will show all your vlans and their network space, if any vlan is missing a `networkSpace` property can you let me know which one so I can figure out how the vlan got to that state?
```bash
slcli call-api SoftLayer_Account getNetworkVlans --mask="mask[id,networkSpace]" 
```

We will also fix this code to not fail if a vlan doesn't have a networkSpace of course.

**Comment by YuriG7** [comment]
>It looks like one of your Vlans might not have a networkSpace attribute...

You are correct. Turns out there are 4. I'll share account number and VLAN IDs with you in a private message.
The above command lists networkSpace as `none` for these 4 VLANS.

Thank you!
