### ISSUE TITLE
Unable to determine file\block storage limits per datacenter

### ISSUE THREAD

**Issue by grnemes** [softlayer/softlayer-python#1879]
**Describe the bug**
When attempting to confirm a recent file\block storage limits increase from IBM cloud, I was unable to determine the new limits.

```
Grants-MBP:Provisioning-Scripts grantnemes$ slcli block volume-limits -d ams03
Usage: slcli block volume-limits [OPTIONS]

Try 'slcli block volume-limits --help' for help.

Error: No such option: -d
Grants-MBP:Provisioning-Scripts grantnemes$ slcli file volume-limits -d ams03
Usage: slcli file volume-limits [OPTIONS]

Try 'slcli file volume-limits --help' for help.

Error: No such option: -d
Grants-MBP:Provisioning-Scripts grantnemes$ slcli file volume-limits
An unexpected error has occured:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/SoftLayer/CLI/core.py", line 182, in main
    cli.main(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/SoftLayer/CLI/file/limit.py", line 27, in cli
    datacenter_name = volume['datacenterName']
KeyError: 'datacenterName'

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues
The following snippet should be able to reproduce the error
Grants-MBP:Provisioning-Scripts grantnemes$ slcli --version
Current: slcli (SoftLayer Command-line) v6.1.2
Latest:  slcli (SoftLayer Command-line) v6.1.4

```

**Expected behavior**
I expected to get the file\block limits per datacenter.

**Version**
Grants-MBP:Provisioning-Scripts grant$ slcli --version
Current: slcli (SoftLayer Command-line) v6.1.2
Latest:  slcli (SoftLayer Command-line) v6.1.4

**Comment by allmightyspiff** [comment]
Can you provide the verbose output like the following. I'm not sure why the response you get back wouldn't have the `datacenter` property. Thanks
```
$ slcli -vvv file volume-limits
Calling: SoftLayer_Network_Storage::getVolumeCountLimits(id=None, mask='', filter='None', args=(), limit=None, offset=None))
Starting new HTTPS connection (1): api.softlayer.com:443
https://api.softlayer.com:443 "POST /xmlrpc/v3.1/SoftLayer_Network_Storage HTTP/1.1" 200 None
Returned Data:
[{"datacenterName": "global", "maximumAvailableCount": 700, "provisionedCount": 51}]
┌────────────┬───────────────────────┬──────────────────┐
│ Datacenter │ MaximumAvailableCount │ ProvisionedCount │
├────────────┼───────────────────────┼──────────────────┤
│   global   │          700          │        51        │
└────────────┴───────────────────────┴──────────────────┘
```

`slcli call-api SoftLayer_Network_Storage getVolumeCountLimits`
will allow you to directly show the volume limits as well.

**Comment by grnemes** [comment]
Here is the verbose output requested. (...and thanks for the api-call reminder!. I'd forgotten about that ability)

```
Grants-MBP:Provisioning-Scripts grantnemes$ slcli -vvv file volume-limits
Calling: SoftLayer_Network_Storage::getVolumeCountLimits(id=None, mask='', filter='None', args=(), limit=None, offset=None))
Starting new HTTPS connection (1): api.softlayer.com:443
https://api.softlayer.com:443 "POST /xmlrpc/v3.1/SoftLayer_Network_Storage HTTP/1.1" 200 None
Returned Data: 
[{'datacenterName': 'global', 'maximumAvailableCount': 700, 'provisionedCount': 2632}, {'datacenterName': 'tor01', 'maximumAvailableCount': 321, 'provisionedCount': 282}, {'datacenterName': 'syd01', 'maximumAvailableCount': 41, 'provisionedCount': 14}, {'datacenterName': 'dal13', 'maximumAvailableCount': 20, 'provisionedCount': 1}, {'datacenterName': 'lon06', 'maximumAvailableCount': 10, 'provisionedCount': 0}, {'datacenterName': 'ams03', 'maximumAvailableCount': 730, 'provisionedCount': 620}, {'maximumAvailableCount': 50, 'provisionedCount': 2632}, {'datacenterName': 'dal10', 'maximumAvailableCount': 20, 'provisionedCount': 1}, {'datacenterName': 'sng01', 'maximumAvailableCount': 75, 'provisionedCount': 61}, {'datacenterName': 'tok02', 'maximumAvailableCount': 5, 'provisionedCount': 1}, {'datacenterName': 'fra02', 'maximumAvailableCount': 400, 'provisionedCount': 347}, {'datacenterName': 'mon01', 'maximumAvailableCount': 110, 'provisionedCount': 56}, {'datacenterName': 'sjc03', 'maximumAvailableCount': 10, 'provisionedCount': 4}, {'datacenterName': 'syd05', 'maximumAvailableCount': 145, 'provisionedCount': 104}, {'datacenterName': 'lon05', 'maximumAvailableCount': 10, 'provisionedCount': 0}, {'datacenterName': 'wdc07', 'maximumAvailableCount': 450, 'provisionedCount': 395}, {'datacenterName': 'sjc04', 'maximumAvailableCount': 275, 'provisionedCount': 238}, {'datacenterName': 'lon04', 'maximumAvailableCount': 10, 'provisionedCount': 0}, {'datacenterName': 'dal12', 'maximumAvailableCount': 20, 'provisionedCount': 2}, {'datacenterName': 'wdc06', 'maximumAvailableCount': 300, 'provisionedCount': 270}, {'datacenterName': 'wdc04', 'maximumAvailableCount': 15, 'provisionedCount': 15}, {'datacenterName': 'lon02', 'maximumAvailableCount': 5, 'provisionedCount': 1}, {'datacenterName': 'syd04', 'maximumAvailableCount': 250, 'provisionedCount': 220}]
An unexpected error has occured:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/SoftLayer/CLI/core.py", line 182, in main
    cli.main(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/SoftLayer/CLI/file/limit.py", line 27, in cli
    datacenter_name = volume['datacenterName']
KeyError: 'datacenterName'

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues
The following snippet should be able to reproduce the error

```

**Comment by allmightyspiff** [comment]
## TODO
- Add a unit test for API response without the `datacenter` property 
```
    {
        "maximumAvailableCount": 50,
        "provisionedCount": 2632
    },
```
- Add `-d <datacenter>` option to allow users to filter by datacenter. https://sldn.softlayer.com/reference/services/SoftLayer_Network_Storage/getVolumeCountLimits/ doesnt accept objectFilters so filtering will need to be done in the command itself I think.
