### ISSUE TITLE
slcli event-log get - xmlrpc.client.Fault: <Fault SoftLayer_Exception_ObjectNotFound: "Unable to find object with id of '10442942'.">

### ISSUE THREAD

**Issue by twoerthle** [softlayer/softlayer-python#1926]
```
slcli -v event-log get -l -1 --metadata

Event, Object, Type, Date, Username, Metadata
slcli : Calling: SoftLayer_Event_Log::getAllObjects(id=None, mask='', filter='{}', args=(), limit=20, offset=0))
At line:1 char:1
+ slcli -v event-log get -l -1 --metadata
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Calling: SoftLa...=20, offset=0)):String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Calling: SoftLayer_User_Customer::getObject(id=10442942, mask='mask[username]', filter='None', args=(), limit=None, offset=None))
An unexpected error has occured:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\SoftLayer\transports\xmlrpc.py", line 102, in __call__
    result = xmlrpc.client.loads(resp.content)[0][0]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\xmlrpc\client.py", line 1031, in loads
    return u.close(), u.getmethodname()
           ^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\xmlrpc\client.py", line 668, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault SoftLayer_Exception_ObjectNotFound: "Unable to find object with id of '10442942'.">

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\SoftLayer\CLI\event_log\get.py", line 61, in cli
    username = user_mgr.get_user(log['userId'], "mask[username]")['username']
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\SoftLayer\managers\user.py", line 69, in get_user
    return self.user_service.getObject(id=user_id, mask=objectmask)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\SoftLayer\API.py", line 610, in call_handler
    return self(name, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\SoftLayer\API.py", line 578, in call
    return self.client.call(self.name, name, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\SoftLayer\API.py", line 302, in call
    return self.transport(request)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\SoftLayer\transports\debug.py", line 42, in __call__
    raise call.exception
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\SoftLayer\transports\debug.py", line 31, in __call__
    call.result = self.transport(call)
                  ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\SoftLayer\transports\xmlrpc.py", line 124, in __call__
    raise _ex(ex.faultCode, ex.faultString) from ex
SoftLayer.exceptions.SoftLayerAPIError: SoftLayerAPIError(SoftLayer_Exception_ObjectNotFound): Unable to find object with id of '10442942'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\SoftLayer\CLI\core.py", line 183, in main
    cli.main(**kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\SoftLayer\CLI\event_log\get.py", line 63, in cli
    except exceptions.SoftLayerAPIError:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'SoftLayer.CLI.exceptions' has no attribute 'SoftLayerAPIError'

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues
The following snippet should be able to reproduce the error
```

**Describe the bug**
Receiving the error `<Fault SoftLayer_Exception_ObjectNotFound: "Unable to find object with id of '10442942'.">` and `AttributeError: module 'SoftLayer.CLI.exceptions' has no attribute 'SoftLayerAPIError'` when making an event_log get call

**Expected behavior**
 IBM Cloud audit/event log results should be returned - https://softlayer-python.readthedocs.io/en/latest/cli/event_log/

**Screenshots**
 N/A

**Version**
```  slcli --version
Current: slcli (SoftLayer Command-line) v6.1.6
Latest:  slcli (SoftLayer Command-line) v6.1.6 
```

**Comment by edsonarios** [comment]
This problem was resolved in PR #1909, but you will only see it in the next version

Now, if your problem continues, let me know so I can solve it as soon as possible, thanks

**Comment by allmightyspiff** [comment]
@twoerthle Cna you try [v6.1.7](https://pypi.org/project/SoftLayer/) and let me know if that fixes the issue for you. Thanks

**Comment by twoerthle** [comment]
@allmightyspiff `v6.1.7` fixed it, thank you!
