### ISSUE TITLE
`slcli  ssl add` souldn't error with no input

### ISSUE THREAD

**Issue by allmightyspiff** [softlayer/softlayer-python#2078]
```
$> slcli  ssl add
An unexpected error has occured:
Traceback (most recent call last):
  File "C:\Users\allmi\Code\py311\Lib\site-packages\SoftLayer\CLI\core.py", line 183, in main
    cli.main(**kwargs)
  File "C:\Users\allmi\Code\py311\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\allmi\Code\py311\Lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allmi\Code\py311\Lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allmi\Code\py311\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allmi\Code\py311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allmi\Code\py311\Lib\site-packages\click\decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allmi\Code\py311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\allmi\Code\py311\Lib\site-packages\SoftLayer\CLI\ssl\add.py", line 31, in cli
    with open(crt, encoding="utf-8") as file_crt:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not NoneType

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues
The following snippet should be able to reproduce the error

```

**Comment by allmightyspiff** [comment]
```
root@cgalloTest:~# slcli -vvv ssl add --crt cert.pem --key key.pem --notes="test ssl cert"
An unexpected error has occured:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/SoftLayer/CLI/core.py", line 183, in main
    cli.main(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/SoftLayer/CLI/ssl/add.py", line 35, in cli
    with open(csr, encoding="utf-8") as file_csr:
TypeError: expected str, bytes or os.PathLike object, not NoneType

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues
The following snippet should be able to reproduce the error

```

Should also nicely handle this case

**Comment by allmightyspiff** [comment]
Add a unit test to make sure only having the 2 required options works as well

**Comment by allmightyspiff** [comment]
```
$> git diff SoftLayer/CLI/security/cert_add.py
diff --git a/SoftLayer/CLI/security/cert_add.py b/SoftLayer/CLI/security/cert_add.py
index 9115e95c..61be1055 100644
--- a/SoftLayer/CLI/security/cert_add.py
+++ b/SoftLayer/CLI/security/cert_add.py
@@ -32,13 +32,14 @@ def cli(env, crt, csr, icc, key, notes):
         template['certificate'] = file_crt.read()
     with open(key, encoding="utf-8") as file_key:
         template['privateKey'] = file_key.read()
-    with open(csr, encoding="utf-8") as file_csr:
-        if csr:
+    if csr:
+        with open(csr, encoding="utf-8") as file_csr:
             body = file_csr.read()
             template['certificateSigningRequest'] = body

-    with open(icc, encoding="utf-8") as file_icc:
-        if icc:
+    if icc:
+        with open(icc, encoding="utf-8") as file_icc:
+

```
