### ISSUE TITLE
Whenever file volume detail is requested on slcli its reported error

### ISSUE THREAD

**Issue by 000YI9** [softlayer/softlayer-python#2154]
**File volume detail is not displayed properly when its executed on SLCLI**

**slcli file volume-detail 609491933**

**Error Screenshots**
slcli file volume-detail 609491933
An unexpected error has occured:
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/SoftLayer/CLI/core.py", line 183, in main
    cli.main(**kwargs)
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/SoftLayer/CLI/file/detail.py", line 132, in cli
    env.fout(table)
  File "/opt/homebrew/lib/python3.11/site-packages/SoftLayer/CLI/environment.py", line 94, in fout
    self.out(self.fmt(output))
             ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/SoftLayer/CLI/environment.py", line 84, in fmt
    return formatting.format_output(output, fmt, self.theme)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/SoftLayer/CLI/formatting.py", line 43, in format_output
    return format_prettytable(data, fmt, theme)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/SoftLayer/CLI/formatting.py", line 86, in format_prettytable
    ptable = table.prettytable(fmt, theme)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/SoftLayer/CLI/formatting.py", line 308, in prettytable
    table.add_row(*row)
  File "/opt/homebrew/lib/python3.11/site-packages/rich/table.py", line 460, in add_row
    raise errors.NotRenderableError(
rich.errors.NotRenderableError: unable to render list; a string or other renderable object is required

*Tried with option as well*
slcli -vvv file volume-detail 609491933
Calling: SoftLayer_Network_Storage::getObject(id=609491933, mask='id,username,password,capacityGb,bytesUsed,snapshotCapacityGb,parentVolume.snapshotSizeBytes,storageType.keyName,serviceResource.datacenter[name],serviceResourceBackendIpAddress,fileNetworkMountAddress,storageTierLevel,provisionedIops,lunId,originalVolumeName,originalSnapshotName,originalVolumeSize,activeTransactionCount,activeTransactions.transactionStatus[friendlyName],replicationPartnerCount,replicationStatus,replicationPartners[id,username,serviceResourceBackendIpAddress,serviceResource[datacenter[name]],replicationSchedule[type[keyname]]],notes', filter='None', args=(), limit=None, offset=None))
Starting new HTTP connection (1): r25436750.application.qadal0901.softlayer.local:80
http://r25436750.application.qadal0901.softlayer.local:80 "POST /v3/sldn/xmlrpc/SoftLayer_Network_Storage HTTP/1.1" 200 None
Returned Data: 
{"capacityGb": 150, "id": 609491933, "username": "SL02SV1414935_187", "activeTransactionCount": 0, "replicationPartnerCount": 1, "fileNetworkMountAddress": "fsf-natestdal0505-fcb-fz.service.softlayer.com:/SL02SV1414935_187/data01", "originalVolumeSize": "20", "provisionedIops": "2000", "replicationStatus": "FAILOVER_COMPLETED", "serviceResourceBackendIpAddress": "fsf-natestdal0505-fcb-fz.service.softlayer.com", "snapshotCapacityGb": "5", "activeTransactions": [{"createDate": "", "elapsedSeconds": 111763, "guestId": "", "hardwareId": "", "id": "", "modifyDate": "", "statusChangeDate": "", "transactionGroup": {"name": "Volume Modification"}, "transactionStatus": {"friendlyName": "In Progress"}}], "parentVolume": {"accountId": 1414935, "capacityGb": 120, "createDate": "2024-05-16T02:28:02-05:00", "guestId": "", "hardwareId": "", "hostId": "", "id": 609491967, "nasType": "SNAPSHOT", "notes": "vol_duplicate_snapshot_2024-05-16_0228", "serviceProviderId": 1, "storageTypeId": "16", "upgradableFlag": true, "username": "SL02SV1414935_187", "serviceResourceBackendIpAddress": "fsf-natestdal0505-fcb-fz.service.softlayer.com", "serviceResourceName": "Storage Type 02 Aggregate natestdal0505-fc-d", "snapshotSizeBytes": "0"}, "replicationPartners": [{"id": 609491945, "username": "SL02SV1414935_187_REP_1", "serviceResourceBackendIpAddress": "fsf-natestdal0505-ffb-fz.service.softlayer.com", "replicationSchedule": {"active": 1, "createDate": "2024-05-16T01:20:19-05:00", "id": 666339, "modifyDate": "", "name": "SL02SV1414935_187_HOURLY_REP", "partnershipId": "", "typeId": 32, "volumeId": 609491933, "type": {"keyname": "REPLICATION_HOURLY"}}, "serviceResource": {"backendIpAddress": "fsf-natestdal0505-ffb-fz.service.softlayer.com", "id": 57365, "name": "Storage Type 02 Aggregate natestdal0505-ff-d", "datacenter": {"name": "dal10"}, "type": {"type": "NETAPP_STOR_AGGR"}}}], "serviceResource": {"backendIpAddress": "fsf-natestdal0505-fcb-fz.service.softlayer.com", "id": 52292, "name": "Storage Type 02 Aggregate natestdal0505-fc-d", "attributes": [{"value": "2", "attributeType": {"keyname": "STAAS_VERSION"}}], "datacenter": {"name": "lon02"}, "type": {"type": "NETAPP_STOR_AGGR"}}, "storageType": {"keyName": "PERFORMANCE_FILE_STORAGE"}}
An unexpected error has occured:
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/SoftLayer/CLI/core.py", line 183, in main
    cli.main(**kwargs)
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 760, in invoke

**Version**
slcli --version
Current: slcli (SoftLayer Command-line) v6.1.5
Latest:  slcli (SoftLayer Command-line) v6.2.2

**Comment by allmightyspiff** [comment]
does this also fail on the latest version? I think I fixed a similar error in the past.
