### ISSUE TITLE
sl server create-options error

### ISSUE THREAD

**Issue by jlax47** [softlayer/softlayer-python#470]
I'm having a problem running create-options for multiple chassis-id's. Here is one example for `sl server create-options 158`:

```
$ sl server create-options 158
An unexpected error has occured:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/SoftLayer/CLI/core.py", line 199, in main
    data = runnable.execute(command_args)
  File "/usr/local/lib/python3.4/site-packages/SoftLayer/CLI/modules/server.py", line 574, in execute
    results = self.get_create_options(ds_options, 'disk')[0]
  File "/usr/local/lib/python3.4/site-packages/SoftLayer/CLI/modules/server.py", line 712, in get_create_options
    disk_type = type_regex.match(disk['description']).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues

```

**Comment by sudorandom** [comment]
This has been merged into master. Until the next release, you'll have to install the module from source: http://softlayer-python.readthedocs.org/en/latest/install.html#from-source
