### ISSUE TITLE
Network Storage/VM Authorization

### ISSUE THREAD

**Issue by doubletb00** [softlayer/softlayer-python#495]
I'm trying to authorize a VM to use some iSCSI storage, and both the methods I'm trying are failing:

client['Network_Storage'].allowAccessFromVirtualGuest([VM object], id=[storage['id']])
Error:
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\SoftLayer\transports.py", line 60, in make_xml_rpc_api_cal
l
    result = utils.xmlrpc_client.loads(response.content,)[0][0]
  File "C:\Python34\lib\xmlrpc\client.py", line 1002, in loads
    return u.close(), u.getmethodname()
  File "C:\Python34\lib\xmlrpc\client.py", line 656, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault SoftLayer_Exception_NotImplemented: 'SoftLayer_Network_Storage::allo
wAccessFromVirtualGuestList is not implemented.'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\IBM_ADMIN\Documents\APIScripts\Testing\test.py", line 41, in <module>
    result1 = client['Network_Storage'].allowAccessFromVirtualGuest(vm, id=stg['id'])
  File "C:\Python34\lib\site-packages\SoftLayer\API.py", line 365, in call_handler
    return self(name, *args, **kwargs)
  File "C:\Python34\lib\site-packages\SoftLayer\API.py", line 333, in call
    return self.client.call(self.name, name, *args, **kwargs)
  File "C:\Python34\lib\site-packages\SoftLayer\API.py", line 181, in call
    proxy=self.proxy)
  File "C:\Python34\lib\site-packages\SoftLayer\transports.py", line 78, in make_xml_rpc_api_cal
l
    ex.faultCode, ex.faultString)
SoftLayer.exceptions.SoftLayerAPIError: SoftLayerAPIError(SoftLayer_Exception_NotImplemented): S
oftLayer_Network_Storage::allowAccessFromVirtualGuestList is not implemented.

client['Virtual_Guest'].allowAccessToNetworkStorage([storage object], id=[vm['id']])
Error:
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\SoftLayer\transports.py", line 60, in make_xml_rpc_api_cal
l
    result = utils.xmlrpc_client.loads(response.content,)[0][0]
  File "C:\Python34\lib\xmlrpc\client.py", line 1002, in loads
    return u.close(), u.getmethodname()
  File "C:\Python34\lib\xmlrpc\client.py", line 656, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault SoftLayer_Exception_NotImplemented: 'SoftLayer_Network_Storage::allo
wAccessFromVirtualGuestList is not implemented.'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\IBM_ADMIN\Documents\APIScripts\Testing\test.py", line 42, in <module>
    result1 = client['Virtual_Guest'].allowAccessToNetworkStorage(stg, id=vm['id'])
  File "C:\Python34\lib\site-packages\SoftLayer\API.py", line 365, in call_handler
    return self(name, *args, **kwargs)
  File "C:\Python34\lib\site-packages\SoftLayer\API.py", line 333, in call
    return self.client.call(self.name, name, *args, **kwargs)
  File "C:\Python34\lib\site-packages\SoftLayer\API.py", line 181, in call
    proxy=self.proxy)
  File "C:\Python34\lib\site-packages\SoftLayer\transports.py", line 78, in make_xml_rpc_api_cal
l
    ex.faultCode, ex.faultString)
SoftLayer.exceptions.SoftLayerAPIError: SoftLayerAPIError(SoftLayer_Exception_NotImplemented): S
oftLayer_Network_Storage::allowAccessFromVirtualGuestList is not implemented.

It looks like both methods are using the same underlying method, which is 'not implemented'. I know this function is also currently broken in the portal - any help would be appreciated. Thanks!

**Comment by underscorephil** [comment]
Howdy!

The best way to get support for an issue like this is by [opening a ticket](http://knowledgelayer.softlayer.com/procedure/create-ticket) in the [customer portal](https://control.softlayer.com/).

If you would, please send me an email with the ticket number(my address is listed on [my profile](https://github.com/underscorephil)) and I will take a peek at it.

-Phil
