### ISSUE TITLE
The "sl server create-options" CLI command raises an exception if used with --disk or --all options

### ISSUE THREAD

**Issue by ggrunin** [softlayer/softlayer-python#513]
The "sl server create-options" CLI when used with --disk or --all options raises the following exception:
An unexpected error has occured:
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\SoftLayer\CLI\core.py", line 199, in main
    data = runnable.execute(command_args)
  File "c:\Python27\lib\site-packages\SoftLayer\CLI\modules\server.py", line 574, in execute
    results = self.get_create_options(ds_options, 'disk')[0]
  File "c:\Python27\lib\site-packages\SoftLayer\CLI\modules\server.py", line 712, in get_create_options
    disk_type = type_regex.match(disk['description']).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by sudorandom** [comment]
This should be resolved in the master branch. A tagged release to pypi will be going out soon (within a week). Until then, you can see this page for help on installing directly from the source.
