### ISSUE TITLE
server list throws error but vs list works

### ISSUE THREAD

**Issue by kylesloan** [softlayer/softlayer-python#532]
slcli server list

An unexpected error has occured:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/SoftLayer-4.0.0-py3.4.egg/SoftLayer/CLI/core.py", line 178, in main
    cli.main()
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 959, in _process_result
    **ctx.params)
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/SoftLayer-4.0.0-py3.4.egg/SoftLayer/CLI/core.py", line 160, in output_result
    output = env.fmt(result)
  File "/usr/local/lib/python3.4/site-packages/SoftLayer-4.0.0-py3.4.egg/SoftLayer/CLI/environment.py", line 45, in fmt
    return formatting.format_output(output, fmt=self.format)
  File "/usr/local/lib/python3.4/site-packages/SoftLayer-4.0.0-py3.4.egg/SoftLayer/CLI/formatting.py", line 36, in format_output
    return str(format_prettytable(data))
  File "/usr/local/lib/python3.4/site-packages/prettytable.py", line 237, in __str__
    return self.__unicode__()
  File "/usr/local/lib/python3.4/site-packages/prettytable.py", line 243, in __unicode__
    return self.get_string()
  File "/usr/local/lib/python3.4/site-packages/prettytable.py", line 984, in get_string
    rows = self._get_rows(options)
  File "/usr/local/lib/python3.4/site-packages/prettytable.py", line 933, in _get_rows
    rows.sort(reverse=options["reversesort"], key=options["sort_key"])
TypeError: unorderable types: NestedDict() < str()

slcli vs list works just fine

I have attempted to run from the latest build with

git clone https://github.com/softlayer/softlayer-python.git && cd softlayer-python && sudo python setup.py install

sl --version                                                                                                                                          
slcli (SoftLayer Command-line), version 4.0.0

I know my softlayer account has a blank server that appears as we were once part of the CoLo in Plano, unsure if this might be related... 

The softlayer support ticket for the blank server is 17157279.

**Comment by sudorandom** [comment]
Thanks for the detail. I believe I have a fix in a PR (#533) right now.

**Comment by sudorandom** [comment]
This should be fixed in master. A bug fix release will likely be done tomorrow.
