### ISSUE TITLE
slcli messaging queue-remove command fails

### ISSUE THREAD

**Issue by MiguelHigorre** [softlayer/softlayer-python#538]
The "slcli messaging queue-remove" command fails, for example when the "slcli messaging queue-remove 5ygqq test1" is executed the below exception is raised:

An unexpected error has occured:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/SoftLayer/CLI/core.py", line 178, in main
    cli.main()
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/SoftLayer/CLI/mq/queue_remove.py", line 30, in cli
    mq_client.delete_queue(queue_name, force)
  File "/usr/local/lib/python3.4/dist-packages/SoftLayer/managers/messaging.py", line 247, in delete_queue
    self._make_request('delete', 'queues/%s' % queue_name, params=params)
  File "/usr/local/lib/python3.4/dist-packages/SoftLayer/managers/messaging.py", line 171, in _make_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.4/dist-packages/requests/models.py", line 834, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues

It looks like the problem is because there are conflicts to process the request by the server.
To reproduce the problem you may follow these steps
- Create a new queue, you can use  "slcli messaging queue-add 5ygqq test1" command
- Push some messages to the queue (slcli -vvv  messaging queue-push 5ygqq test1 "some message")
- Get queue messages by using "slcli -vvv  messaging queue-add 5ygqq test1" command
- Try to delete the queue using "slcli -vvv  messaging queue-remove 5ygqq test1" command

**Comment by sudorandom** [comment]
@MiguelHigorre this is a case where it's not entirely a bug, but the CLI should display a much nicer message.

409 errors happen because there are messages in the queue or subscriptions on a topic. The default behavior is to not allow these things to happen, but it can be overridden by using the force=true query parameter in the API. In the CLI, you can use the `--force` option. For example: `slcli messaging queue-remove --force 5ygqq test1`

I'll keep this issue open to track making the error messages better, since this is a fairly normal things to come across.
