### ISSUE TITLE
unexpected error while waiting on a vs instance to be ready 

### ISSUE THREAD

**Issue by jkeenleyside** [softlayer/softlayer-python#545]
slcli vs ready --wait=600 'john01' 
An unexpected error has occured:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/SoftLayer/CLI/core.py", line 180, in main
    cli.main()
  File "/Library/Python/2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
TypeError: cli() takes exactly 3 arguments (2 given)

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues

**Comment by jkeenleyside** [comment]
Here are the versions of the software I am using:
>>> import six
>>> six.__version__
'1.9.0'
>>> import SoftLayer
>>> SoftLayer.__version__
'v4.0.2'

**Comment by Neetuj** [comment]
missing the env in SoftLayer/CLI/virt/ready.py

**Comment by Neetuj** [comment]
#546

**Comment by sudorandom** [comment]
The fix is in master. This will be released in 2-3 days (waiting for potentially more bug reports). Thanks @jkeenleyside  for the bug report. Thanks @Neetuj for fixing it.

**Comment by sudorandom** [comment]
The release is waiting on the couple of pull requests which fix other bugs to be completed. Sorry for the delay.
