### ISSUE TITLE
Error creating new iscsi device

### ISSUE THREAD

**Issue by sidick** [softlayer/softlayer-python#549]
I'm getting an error when trying to create a new iscsi entry using slcli version 4.0.2:

To my eyes it looks like no data is being returned into the item_prices array.

```
$ slcli --debug 2 iscsi create --size 5 --datacenter lon02
POST https://api.softlayer.com/xmlrpc/v3.1/SoftLayer_Product_Package
Starting new HTTPS connection (1): api.softlayer.com
An unexpected error has occured:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/CLI/core.py", line 180, in main
    cli.main()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/CLI/iscsi/create.py", line 23, in cli
    iscsi_mgr.create_iscsi(size=size, location=datacenter)
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/managers/iscsi.py", line 65, in create_iscsi
    categorycode='iscsi')
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/managers/iscsi.py", line 31, in _find_item_prices
    item_price = item_prices[0]['prices'][0]['id']
IndexError: list index out of range

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues
```

**Comment by Neetuj** [comment]
This is another case of "referenced before establishing it exists". 
Should we have a general wrapper to do that check before every reference?

**Comment by sudorandom** [comment]
It looks like all iscsi items in the aux (0) package have been removed, which makes ordering iscsi this way (or at all?) impossible... This should be handled better, but even with a more gracious error message, it won't help ever succeed the way it is now.

**Comment by sudorandom** [comment]
It turns out the iscsi product that was named "iscsi" has been disabled for ordering in favor of a couple newer/similar products. Hopefully I'll get more details on this.

**Comment by sidick** [comment]
Yep, it looks like the new Block Storage product has pretty much taken over

**Comment by kbroughton** [comment]
Ok, so how is one supposed to create regular block storage now.  "Block Storage" for softlayer is SAN based which i presume is more expensive than Cinder based technology.  If your needs are only Direct Attached Storage then it's perhaps overkill.

Also, I use the python sdk which exists for iscsi but not for Block Storage as far as i can tell.  How am i supposed to automate block storage creation.  If iscsi is truly deprecated, the docs should reflect that.
https://softlayer-api-python-client.readthedocs.org/en/latest/api/managers/iscsi/
