### ISSUE TITLE
load balancer service-add command does not work through cli

### ISSUE THREAD

**Issue by fyatzeck** [softlayer/softlayer-python#550]
The load balancer service-add command fails with error below while attempting to add service to the existing service group using port 15672.

Here is my command syntax:
slcli loadbal service-add local:79187 --port=15672 --weight=1 --healthcheck-type=4 --ip=174.37.219.102

I have also tried with ip address argument name spelled out as "--ip-address" resulting same error.  Is my syntax incorrect or is this a bug?

An unexpected error has occured:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/SoftLayer-4.0.0-py2.7.egg/SoftLayer/CLI/core.py", line 180, in main
    cli.main()
  File "/usr/local/lib/python2.7/site-packages/click-4.0-py2.7.egg/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click-4.0-py2.7.egg/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click-4.0-py2.7.egg/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click-4.0-py2.7.egg/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click-4.0-py2.7.egg/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click-4.0-py2.7.egg/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click-4.0-py2.7.egg/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
TypeError: cli() got an unexpected keyword argument 'ip'

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues

**Comment by MiguelHigorre** [comment]
Hello,

It looks that there is an extra "-" character at line 27 in service_add.py module
@click.option('--ip-address', '--ip',
Changing that line to 
@click.option('--ip-address', '-ip',
It works for me, however the format for cli command sohuld be the following 
slcli -vvv loadbal service-add --enabled --port=2244 --weight=1 --healthcheck-type=4 -ip=50.97.140.250 '12862:72952'
where '12862:72952' is 'loadbal_id, group_id'
