### ISSUE TITLE
slcli vlan list raises "KeyError: 'datacenter'" 

### ISSUE THREAD

**Issue by MiguelHigorre** [softlayer/softlayer-python#552]
The "slcli vlan list" command raises "KeyError: 'datacenter'", below is the traceback output.

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/SoftLayer/CLI/core.py", line 178, in main
    cli.main()
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/SoftLayer/CLI/vlan/list.py", line 46, in cli
    vlan['primaryRouter']['datacenter']['name'],
KeyError: 'datacenter'

It seems to be that this exception is raised because some vlan object returns empty  when try to accede to datacenter property (vlan['primaryRouter']['datacenter']['name']).

The issue was reproduced with latest SL python API client and python 3.4.

**Comment by underscorephil** [comment]
@MiguelHigorre can you confirm that this issue has been resolved?

**Comment by MiguelHigorre** [comment]
@underscorephil, the issue is fixed, but it looks like the fix is not available on pypi repository yet.

**Comment by underscorephil** [comment]
Considering this closed. Fix will be in next release.
