### ISSUE TITLE
vs ready command

### ISSUE THREAD

**Issue by c4po** [softlayer/softlayer-python#557]
Hi

Does the ```slcli vs ready``` command implemented in the v4?

I'm getting error message like when using it

```
slcli vs ready --wait 900 xxxxxxx
An unexpected error has occured:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/SoftLayer/CLI/core.py", line 180, in main
    cli.main()
  File "/usr/lib/python2.6/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.6/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.6/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.6/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.6/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
TypeError: cli() takes exactly 3 non-keyword arguments (0 given)

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues
```

**Comment by sudorandom** [comment]
This should be fixed in master (via #545), but hasn't made it to a release yet.
