### ISSUE TITLE
AttributeError with slcli getting details of virtual server

### ISSUE THREAD

**Issue by ajohnson1** [softlayer/softlayer-python#592]
SoftLayer-4.0.4

c:\Python27>scripts\slcli vs detail 11115103
An unexpected error has occured:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\SoftLayer\CLI\core.py", line 181, in main
    cli.main()
  File "C:\Python27\lib\site-packages\click\core.py", line 644, in main
    rv = self.invoke(ctx)
  File "C:\Python27\lib\site-packages\click\core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Python27\lib\site-packages\click\core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Python27\lib\site-packages\click\core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python27\lib\site-packages\click\core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "C:\Python27\lib\site-packages\click\decorators.py", line 64, in new_func

    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "C:\Python27\lib\site-packages\click\core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "C:\Python27\lib\site-packages\SoftLayer\CLI\virt\detail.py", line 73, in
 cli
    'username') or formatting.blank(),
  File "C:\Python27\lib\site-packages\SoftLayer\utils.py", line 40, in lookup
    return lookup(dic.get(key, {}), *keys)
  File "C:\Python27\lib\site-packages\SoftLayer\utils.py", line 40, in lookup
    return lookup(dic.get(key, {}), *keys)
AttributeError: 'list' object has no attribute 'get'

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues

This problem only occurs on some of the virtual servers, but for those it does, it happens all the time with the above command.

It might be due to the attribute billingItem.

**Comment by sudorandom** [comment]
You're right that it's because of billingItem. It looks like you don't have permission and the current code doesn't handle that case as expected. I opened a PR with the fix for this. Thanks for raising the issue!
