### ISSUE TITLE
got an unexpected keyword argument 'tags'

### ISSUE THREAD

**Issue by username-is-already-taken2** [softlayer/softlayer-python#597]
Hi there

I came across an error when creating VS and providing tags either in the form of -g or --tag

C:\Python34\Scripts>slcli vs create --test --hostname OS --domain vm.local --cpu 1 --memory 1024 --os WIN_LATEST_64 --datacenter lon02 --tag 1234
An unexpected error has occured:
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\SoftLayer\CLI\core.py", line 181, in main
    cli.main()
  File "C:\Python34\lib\site-packages\click\core.py", line 644, in main
    rv = self.invoke(ctx)
  File "C:\Python34\lib\site-packages\click\core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Python34\lib\site-packages\click\core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Python34\lib\site-packages\click\core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python34\lib\site-packages\click\core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "C:\Python34\lib\site-packages\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "C:\Python34\lib\site-packages\click\core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "C:\Python34\lib\site-packages\SoftLayer\CLI\virt\create.py", line 92, in cli
    result = vsi.verify_create_instance(**data)
  File "C:\Python34\lib\site-packages\SoftLayer\managers\vs.py", line 426, in verify_create_instance
    create_options = self._generate_create_dict(**kwargs)
TypeError: _generate_create_dict() got an unexpected keyword argument 'tags'

**Comment by sudorandom** [comment]
I remember this being an issue a while ago. Can you check the version that you're using?

```python
>>> import SoftLayer
>>> print(SoftLayer.__version__)
```

**Comment by username-is-already-taken2** [comment]
I'm using 4.0.4

C:\Python34\Scripts>slcli --version
slcli (SoftLayer Command-line), version 4.0.4

**Comment by sudorandom** [comment]
Thanks for the report(s). I'll look at this as soon as I have the spare cycles.

PS: I had a nice chuckle at your username.
