### ISSUE TITLE
FileNotFoundError - Conflict between config file and shell history

### ISSUE THREAD

**Issue by username-is-already-taken2** [softlayer/softlayer-python#625]
Hi there

I've come across an issue when trying to use the shell within slcli.

I'll be upfront it maybe a feature of my using windows but here goes.

when I run the slcli config setup command it writes it out to a file just called "softlayer" within my appdata roaming folder.  I don't know if it should be called .softlayer or softlayer.conf either way when I'm into the shell and run a command  I get an error 

(1)> clearTraceback (most recent call last):
  File "c:\python34\lib\site-packages\SoftLayer\shell\core.py", line 58, in cli
    history=history,
  File "c:\python34\lib\site-packages\prompt_toolkit\shortcuts.py", line 415, in get_input
    document = cli.run(reset_current_buffer=False)
  File "c:\python34\lib\site-packages\prompt_toolkit\interface.py", line 313, in run
    self.eventloop.run(self.input, self.create_eventloop_callbacks())
  File "c:\python34\lib\site-packages\prompt_toolkit\eventloop\win32.py", line 71, in run
    callbacks.feed_key(k)
  File "c:\python34\lib\site-packages\prompt_toolkit\interface.py", line 723, in feed_key
    self._active_cli.input_processor.feed_key(key_press)
  File "c:\python34\lib\site-packages\prompt_toolkit\key_binding\input_processor.py", line 171, in feed_key
    self._process_coroutine.send(key_press)
  File "c:\python34\lib\site-packages\prompt_toolkit\key_binding\input_processor.py", line 143, in _process
    self._call_handler(matches[-1], key_sequence=buffer)
  File "c:\python34\lib\site-packages\prompt_toolkit\key_binding\input_processor.py", line 183, in _call_handler
    handler.call(event)
  File "c:\python34\lib\site-packages\prompt_toolkit\key_binding\registry.py", line 30, in call
    return self._handler(event)
  File "c:\python34\lib\site-packages\prompt_toolkit\key_binding\bindings\utils.py", line 30, in wrapper
    handler_func(event)
  File "c:\python34\lib\site-packages\prompt_toolkit\key_binding\bindings\basic.py", line 179, in _
    b.accept_action.validate_and_handle(event.cli, b)
  File "c:\python34\lib\site-packages\prompt_toolkit\buffer.py", line 77, in validate_and_handle
    buffer.append_to_history()
  File "c:\python34\lib\site-packages\prompt_toolkit\buffer.py", line 928, in append_to_history
    self.history.append(self.text)
  File "c:\python34\lib\site-packages\prompt_toolkit\history.py", line 105, in append
    with open(self.filename, 'ab') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Gary\\AppData\\Roaming\\softlayer\\history'

It seems that its trying to writeout to file called history in a folder called softlayer 
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Gary\\AppData\\Roaming\\softlayer\\history'

but that doesnt work becuase theres already a file call softlayer

Hope this helps.

Thanks

**Comment by sudorandom** [comment]
Sorry for the delay in response. Yes, this is ultimately because of Windows... This is a bug though, so thanks for the report.
