### ISSUE TITLE
FirewallManager.edit_dedicated_fwl_rules docs say it takes a dict, but it only accepts a list.

### ISSUE THREAD

**Issue by TaylorSMarks** [softlayer/softlayer-python#634]
First off, I'm not quite clear - what is FirewallManager.edit_dedicated_fwl_rules supposed to do? I'd like to add a single rule... I'm concerned I might accidentally replace all of my rules with just one rule, which would be really bad given I have 41 existing rules.

Anyways, here's the code that I've written:

~~~
# client and ip are already defined elsewhere.

from SoftLayer import FirewallManager

fm = FirewallManager(client)

firewallID = fm.get_firewalls()[0]['networkVlanFirewall']['id']  # I only have one firewall, so this will get it fine.

rules = fm.get_dedicated_fwl_rules(firewallID)

fm.edit_dedicated_fwl_rules(firewallID, {
    'action'                   : 'permit',
    'destinationIpAddress'     : ip,
    'destinationIpCidr'        : 32,
    'destinationIpSubnetMask'  : '255.255.255.255',
    'destinationPortRangeEnd'  : 65535,
    'destinationPortRangeStart': 1,
    'orderValue'               : rules[-1]['orderValue'] + 1,
    'protocol'                 : 'tcp',
    'sourceIpAddress'          : '0.0.0.0',
    'sourceIpCidr'             : 0,
    'sourceIpSubnetMask'       : '0.0.0.0',
    'version'                  : 4
})
~~~

When I try running this, I get this stack trace:

~~~
Traceback (most recent call last):
  File "<stdin>", line 14, in <module>
    'version'                  : 4
  File "C:\Python27\lib\site-packages\SoftLayer\managers\firewall.py", line 267, in edit_dedicated_fwl_rules
    return svc.createObject(template)
  File "C:\Python27\lib\site-packages\SoftLayer\API.py", line 363, in call_handler
    return self(name, *args, **kwargs)
  File "C:\Python27\lib\site-packages\SoftLayer\API.py", line 331, in call
    return self.client.call(self.name, name, *args, **kwargs)
  File "C:\Python27\lib\site-packages\SoftLayer\API.py", line 227, in call
    return self.transport(request)
  File "C:\Python27\lib\site-packages\SoftLayer\transports.py", line 160, in __call__
    raise _ex(ex.faultCode, ex.faultString)
SoftLayer.exceptions.SoftLayerAPIError: SoftLayerAPIError(SoftLayer_Exception_Public): Each rule must have a distinct order value, '' has a duplicate.
~~~

It says that I have a duplicate rule `orderValue` of `''`, but I clearly set it to a number. This suggests to me that I wasn't actually supposed to pass a dictionary representing a rule directly in as a second argument to `edit_dedicated_fwl_rules`... but reading over the code I can't tell what I should actually pass in. I think there's either a bug here that it isn't reading my orderValue property properly, or there's a documentation defect in that I'm not sure what I should be passing in here (or maybe both).

**Comment by TaylorSMarks** [comment]
I discovered today that there are unit tests for this module, and they cover this exact method.

Took a look at the example call and found that in the example, it calls the method with a list of 3 dicts of rules. So I modified my code to take in the existing rule list, append my new rule to it, and then pass that to `edit_dedicated_fwl_rules`. That works perfectly.

~~~
# client and ip are already defined elsewhere.

from SoftLayer import FirewallManager

fm = FirewallManager(client)

firewallID = fm.get_firewalls()[0]['networkVlanFirewall']['id']  # I only have one firewall, so this will get it fine.

rules = fm.get_dedicated_fwl_rules(firewallID)

lastRuleOrderValue = max(rule['orderValue'] for rule in rules)

 rules.append({
    'action'                   : 'permit',
    'destinationIpAddress'     : ip,
    'destinationIpCidr'        : 32,
    'destinationIpSubnetMask'  : '255.255.255.255',
    'destinationPortRangeEnd'  : 65535,
    'destinationPortRangeStart': 1,
    'orderValue'               : lastRuleOrderValue + 1,
    'protocol'                 : 'tcp',
    'sourceIpAddress'          : '0.0.0.0',
    'sourceIpCidr'             : 0,
    'sourceIpSubnetMask'       : '0.0.0.0',
    'version'                  : 4
})

fm.edit_dedicated_fwl_rules(firewallID, rules)
~~~

So this appears to just be a documentation defect. I suggest changing the doc string to the following for this function:

~~~
def edit_dedicated_fwl_rules(self, firewall_id, rules):
    """Edit the rules for dedicated firewall. All existing rules on the firewall will be replaced with provided list of rules.

    :param integer firewall_id: the instance ID of the dedicated firewall
    :param list rules: the rules to be pushed on the firewall
    """
~~~

Note the added sentence and the change of the param type from a dict to a list.
