### ISSUE TITLE
slcli --help - Error on Windows 10

### ISSUE THREAD

**Issue by paulmcgrail** [softlayer/softlayer-python#706]
### Expected Behavior
Display the Help Message 

### Actual Behavior

C:\Users\paulm>slcli --help
An unexpected error has occured:
Traceback (most recent call last):
  File "C:\Users\paulm\AppData\Local\Programs\Python\Python35-32\lib\site-packages\softlayer-5.0.0-py3.5.egg\SoftLayer\CLI\core.py", line 163, in main
    cli.main(**kwargs)
  File "C:\Users\paulm\AppData\Local\Programs\Python\Python35-32\lib\site-packages\click\core.py", line 695, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "C:\Users\paulm\AppData\Local\Programs\Python\Python35-32\lib\site-packages\click\core.py", line 620, in make_context
    self.parse_args(ctx, args)
  File "C:\Users\paulm\AppData\Local\Programs\Python\Python35-32\lib\site-packages\click\core.py", line 1012, in parse_args
    rest = Command.parse_args(self, ctx, args)
  File "C:\Users\paulm\AppData\Local\Programs\Python\Python35-32\lib\site-packages\click\core.py", line 874, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "C:\Users\paulm\AppData\Local\Programs\Python\Python35-32\lib\site-packages\click\core.py", line 1398, in handle_parse_result
    self.callback, ctx, self, value)
  File "C:\Users\paulm\AppData\Local\Programs\Python\Python35-32\lib\site-packages\click\core.py", line 77, in invoke_param_callback
    return callback(ctx, param, value)
  File "C:\Users\paulm\AppData\Local\Programs\Python\Python35-32\lib\site-packages\click\core.py", line 803, in show_help
    echo(ctx.get_help(), color=ctx.color)
  File "C:\Users\paulm\AppData\Local\Programs\Python\Python35-32\lib\site-packages\click\core.py", line 495, in get_help
    return self.command.get_help(self)
  File "C:\Users\paulm\AppData\Local\Programs\Python\Python35-32\lib\site-packages\click\core.py", line 824, in get_help
    self.format_help(ctx, formatter)
  File "C:\Users\paulm\AppData\Local\Programs\Python\Python35-32\lib\site-packages\click\core.py", line 839, in format_help
    self.format_options(ctx, formatter)
  File "C:\Users\paulm\AppData\Local\Programs\Python\Python35-32\lib\site-packages\click\core.py", line 950, in format_options
    self.format_commands(ctx, formatter)
  File "C:\Users\paulm\AppData\Local\Programs\Python\Python35-32\lib\site-packages\click\core.py", line 995, in format_commands
    cmd = self.get_command(ctx, subcommand)
  File "C:\Users\paulm\AppData\Local\Programs\Python\Python35-32\lib\site-packages\softlayer-5.0.0-py3.5.egg\SoftLayer\CLI\core.py", line 65, in get_command
    module = env.get_command(*new_path)
  File "C:\Users\paulm\AppData\Local\Programs\Python\Python35-32\lib\site-packages\softlayer-5.0.0-py3.5.egg\SoftLayer\CLI\environment.py", line 89, in get_command
    return self.commands[path_str].load()
  File "C:\Users\paulm\AppData\Local\Programs\Python\Python35-32\lib\site-packages\softlayer-5.0.0-py3.5.egg\SoftLayer\CLI\environment.py", line 165, in load
    module = importlib.import_module(self.import_path)
  File "C:\Users\paulm\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\paulm\AppData\Local\Programs\Python\Python35-32\lib\site-packages\softlayer-5.0.0-py3.5.egg\SoftLayer\shell\core.py", line 19, in <module>
    from pygments import token
ImportError: No module named 'pygments'

### Environment Information
Operating System: Windows 10
softlayer-python version (`slcli --version`):

C:\Users\paulm>slcli --version
slcli (SoftLayer Command-line), version 5.0.0

**Comment by sudorandom** [comment]
The short term fix is to manually install pygments (`pip install pygments`). The real fix is in the works: #709

**Comment by sudorandom** [comment]
v5.0.1 has been released and should resolve your issue.
