### ISSUE TITLE
Import Error on Python CLI

### ISSUE THREAD

**Issue by johnhamner** [softlayer/softlayer-python#708]
I have had a lot of trouble installing the CLI due to recent updates on El Capitan.  I updated Python via brew and now I am getting this error. Is this because of the recent Security updates on El Capitan? Any help is appreciated.

### Output
Johns-MacBook-Pro-2:~ jhamner$ slcli
An unexpected error has occured:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/CLI/core.py", line 163, in main
    cli.main(**kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 695, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/Library/Python/2.7/site-packages/click/core.py", line 620, in make_context
    self.parse_args(ctx, args)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1009, in parse_args
    echo(ctx.get_help(), color=ctx.color)
  File "/Library/Python/2.7/site-packages/click/core.py", line 495, in get_help
    return self.command.get_help(self)
  File "/Library/Python/2.7/site-packages/click/core.py", line 824, in get_help
    self.format_help(ctx, formatter)
  File "/Library/Python/2.7/site-packages/click/core.py", line 839, in format_help
    self.format_options(ctx, formatter)
  File "/Library/Python/2.7/site-packages/click/core.py", line 950, in format_options
    self.format_commands(ctx, formatter)
  File "/Library/Python/2.7/site-packages/click/core.py", line 995, in format_commands
    cmd = self.get_command(ctx, subcommand)
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/CLI/core.py", line 65, in get_command
    module = env.get_command(*new_path)
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/CLI/environment.py", line 89, in get_command
    return self.commands[path_str].load()
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/CLI/environment.py", line 165, in load
    module = importlib.import_module(self.import_path)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/shell/core.py", line 19, in <module>
    from pygments import token
ImportError: No module named pygments

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues

### Environment Information
Operating System: OS X El Capitan Version 10.11
softlayer-python version (`slcli --version`):5.0

**Comment by sudorandom** [comment]
The short term fix is to manually install pygments (`pip install pygments`). The real fix is in the works: #709

**Comment by johnhamner** [comment]
Thank you!

**Comment by sudorandom** [comment]
v5.0.1 has been released and should resolve your issue in the long term. Thanks for the bug report.
