### ISSUE TITLE
can not get vlan detail

### ISSUE THREAD

**Issue by cuiliquan** [softlayer/softlayer-python#711]
It throw an exception when I run slcli vlan detail 1154143 to get the vlan detail, could you please take look at the issue?

An unexpected error has occured:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/SoftLayer/CLI/core.py", line 163, in main
    cli.main(**kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/SoftLayer/CLI/vlan/detail.py", line 42, in cli
    for subnet in vlan['subnets']:
KeyError: 'subnets'

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues

**Comment by sudorandom** [comment]
The fix for this has been pushed into master. Until the next release, you can install softlayer-python from the repo directly by following the instructions here: http://softlayer-python.readthedocs.org/en/latest/install.html#from-source
