### ISSUE TITLE
slcli vlan detail error

### ISSUE THREAD

**Issue by bkonick** [softlayer/softlayer-python#724]
### Expected Behavior
Get details of a vlan
### Actual Behavior
slcli vlan detail VLANID
An unexpected error has occured:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/CLI/core.py", line 163, in main
    cli.main(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/CLI/vlan/detail.py", line 42, in cli
    for subnet in vlan['subnets']:
KeyError: 'subnets'

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues
### Environment Information
Operating System: RHEL 6.7
softlayer-python version (`slcli --version`): 5.0.1
python version: 2.7.11

**Comment by bkonick** [comment]
Oops, just saw that this is going to be fixed in the next release.  Sorry for the duplicate issue!
