### ISSUE TITLE
slcli image list complains about unicode errors

### ISSUE THREAD

**Issue by ptasnik** [softlayer/softlayer-python#771]
### Expected Behavior

slcli image list should work
### Actual Behavior

slcli image list complains (see error)

It had been working perfectly for many months and suddenly I can not run 'image list' which breaks my automation.  On my Linux system it works and shows a suspect looking entry
      fd16452d-1a03-48b7-ae52-6b1d15632051 :          ã��CEDECã��Photon Handson image           :       System       :   Public   :  363380 :

I use cygwin and I have tried various locale settings like en_US.CP1252 and C.UTF-8, etc.

I have version 5.2 which seems to address a similar issue.  Any ideas?

I was able to work around it by using the --private option.

---

tasnik@DFDDSGFSDSSFDSG ~
$ slcli image list
An unexpected error has occured:
Traceback (most recent call last):
  File "c:\users\ibm_admin\appdata\local\programs\python\python35-32\lib\site-packages\SoftLayer\CLI\core.py", line 163, in main
    cli.main(*_kwargs)
  File "c:\users\ibm_admin\appdata\local\programs\python\python35-32\lib\site-packages\click-6.6-py3.5.egg\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "c:\users\ibm_admin\appdata\local\programs\python\python35-32\lib\site-packages\click-6.6-py3.5.egg\click\core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\ibm_admin\appdata\local\programs\python\python35-32\lib\site-packages\click-6.6-py3.5.egg\click\core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\ibm_admin\appdata\local\programs\python\python35-32\lib\site-packages\click-6.6-py3.5.egg\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, *_ctx.params)
  File "c:\users\ibm_admin\appdata\local\programs\python\python35-32\lib\site-packages\click-6.6-py3.5.egg\click\core.py", line 534, in invoke
    return callback(_args, *_kwargs)
  File "c:\users\ibm_admin\appdata\local\programs\python\python35-32\lib\site-packages\click-6.6-py3.5.egg\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, _args[1:], *_kwargs)
  File "c:\users\ibm_admin\appdata\local\programs\python\python35-32\lib\site-packages\click-6.6-py3.5.egg\click\core.py", line 534, in invoke
    return callback(_args, *_kwargs)
  File "c:\users\ibm_admin\appdata\local\programs\python\python35-32\lib\site-packages\SoftLayer\CLI\image\list.py", line 58, in cli
    env.fout(table)
  File "c:\users\ibm_admin\appdata\local\programs\python\python35-32\lib\site-packages\SoftLayer\CLI\environment.py", line 56, in fout
    self.out(self.fmt(output), newline=newline)
  File "c:\users\ibm_admin\appdata\local\programs\python\python35-32\lib\site-packages\SoftLayer\CLI\environment.py", line 43, in out
    click.echo(output, nl=newline)
  File "c:\users\ibm_admin\appdata\local\programs\python\python35-32\lib\site-packages\click-6.6-py3.5.egg\click\utils.py", line 259, in echo
    file.write(message)
  File "c:\users\ibm_admin\appdata\local\programs\python\python35-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 70318-70319: character maps to <undefined>

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues

---
### Environment Information

Operating System:
softlayer-python version (`slcli --version`):
Windows . cygwin slcli (SoftLayer Command-line), version 5.2.0

**Comment by allmightyspiff** [comment]
```
$ slcli image list | grep 363380
680089   Kitase-Image                                                                        SYSTEM        PUBLIC   363380
1288413  invalid                                                                             SYSTEM        PUBLIC   363380
```

```
$ slcli image detail 1288413
:....................:......................................:
:               name : value                                :
:....................:......................................:
:                 id : 1288413                              :
:  global_identifier : fd16452d-1a03-48b7-ae52-6b1d15632051 :
:               name : ãCEDECãPhoton Handson image      :
:             status : Active                               :
: active_transaction : -                                    :
:            account : 363380                               :
:         visibility : Public                               :
:               type : System                               :
:               flex : False                                :
:               note : Photonã¤ã¡ã¼ã¸                   :
:            created : 2016-08-19T01:01:52-07:00            :
:         disk_space : 29.99G                               :
:        datacenters : tok02,wdc01                          :
:....................:......................................:
```

Work on OSX, I'll need to test in windows to see how to fix this.

**Comment by allmightyspiff** [comment]
Will be added in the next release.
