### ISSUE TITLE
Can not create iscsi storage

### ISSUE THREAD

**Issue by rodrabe** [softlayer/softlayer-python#777]
### Expected Behavior

Storage created
### Actual Behavior

sl iscsi create -s 5 -d sjc01 create iscsi storage

```
=== REQUEST ===
POST https://api.softlayer.com/xmlrpc/v3.1/SoftLayer_Product_Package
{'Content-Type': 'application/xml', 'Accept-Encoding': 'gzip, deflate, compress', 'Accept': '*/*', 'User-Agent': 'SoftLayer Python v3.3.1'}
<?xml version='1.0'?>
<methodCall>
<methodName>getItems</methodName>
<params>
<param>
<value><struct>
<member>
<name>headers</name>
<value><struct>
<member>
<name>SoftLayer_Product_PackageObjectFilter</name>
<value><struct>
<member>
<name>items</name>
<value><struct>
<member>
<name>capacity</name>
<value><struct>
<member>
<name>operation</name>
<value><int>5</int></value>
</member>
</struct></value>
</member>
<member>
<name>categories</name>
<value><struct>
<member>
<name>categoryCode</name>
<value><struct>
<member>
<name>operation</name>
<value><string>iscsi</string></value>
</member>
</struct></value>
</member>
</struct></value>
</member>
</struct></value>
</member>
</struct></value>
</member>
<member>
<name>authenticate</name>
<value><struct>
<member>
<name>username</name>
<value><string>USERNAME</string></value>
</member>
<member>
<name>apiKey</name>
<value><string>API_KEY</string></value>
</member>
</struct></value>
</member>
<member>
<name>SoftLayer_ObjectMask</name>
<value><struct>
<member>
<name>mask</name>
<value><string>mask[id,capacity,prices[id]]</string></value>
</member>
</struct></value>
</member>
<member>
<name>SoftLayer_Product_PackageInitParameters</name>
<value><struct>
<member>
<name>id</name>
<value><int>0</int></value>
</member>
</struct></value>
</member>
</struct></value>
</member>
</struct></value>
</param>
</params>
</methodCall>

Starting new HTTPS connection (1): api.softlayer.com
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
"POST /xmlrpc/v3.1/SoftLayer_Product_Package HTTP/1.1" 200 110
=== RESPONSE ===
{'Content-Length': '110', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Server': 'Apache', 'SoftLayer-Total-Items': '0', 'Connection': 'close', 'ntCoent-Length': '126', 'Cache-Control': 'private', 'Date': 'Thu, 13 Oct 2016 23:02:51 GMT', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Type': 'text/xml'}
<?xml version="1.0" encoding="utf-8"?>
<params>
<param>
 <value>
  <array>
   <data/>
  </array>
 </value>
</param>
</params>

An unexpected error has occured:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/SoftLayer/CLI/core.py", line 199, in main
    data = runnable.execute(command_args)
  File "/usr/local/lib/python2.7/dist-packages/SoftLayer/CLI/modules/iscsi.py", line 84, in execute
    iscsi_mgr.create_iscsi(size=size, location=location)
  File "/usr/local/lib/python2.7/dist-packages/SoftLayer/managers/iscsi.py", line 67, in create_iscsi
    categorycode='iscsi')
  File "/usr/local/lib/python2.7/dist-packages/SoftLayer/managers/iscsi.py", line 31, in _find_item_prices
    item_price = item_prices[0]['prices'][0]['id']
IndexError: list index out of range
```

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues
### Environment Information

Operating System:Ubuntu 12.04.1
softlayer-python version (`slcli --version`):
v3.3.1

**Comment by sudorandom** [comment]
@rodrabe: you inadvertently posted your API key along with the text of this issue. I masked it out, but I recommend re-creating it immediately.

**Comment by camporter** [comment]
Hello, your version of softlayer-python is from 2 years ago. If you can, try and upgrade to the latest version available and try the create again. That version is making an assumption that a product is available from the API, when that isn't the case exactly.

**Comment by allmightyspiff** [comment]
Block (or ISCSI) storage now needs to be ordered with the  following command.
```
slcli block volume-order
```
