### ISSUE TITLE
AttributeError: 'module' object has no attribute 'FRAME'

### ISSUE THREAD

**Issue by sotnickd** [softlayer/softlayer-python#779]
**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**

### Expected Behavior

Expected to setup slcli (slcli -setup) with internal API URL

### Actual Behavior

Throws exception: 

Endpoint (public|private|custom) [public]: custom
Endpoint URL [https://api.softlayer.com/xmlrpc/v3.1]: https://api.service.softlayer.com/xmlrpc/v3.1/
Timeout [0]: 240
An unexpected error has occured:
Traceback (most recent call last):
 File "/usr/lib/python2.7/site-packages/SoftLayer-5.2.0-py2.7.egg/SoftLayer/CLI/core.py", line 163, in main
   cli.main(**kwargs)
 File "/usr/lib/python2.7/site-packages/click-7.0_dev-py2.7.egg/click/core.py", line 697, in main
   rv = self.invoke(ctx)
 File "/usr/lib/python2.7/site-packages/click-7.0_dev-py2.7.egg/click/core.py", line 1071, in invoke
   return _process_result(sub_ctx.command.invoke(sub_ctx))
 File "/usr/lib/python2.7/site-packages/click-7.0_dev-py2.7.egg/click/core.py", line 898, in invoke
   return ctx.invoke(self.callback, **ctx.params)
 File "/usr/lib/python2.7/site-packages/click-7.0_dev-py2.7.egg/click/core.py", line 535, in invoke
   return callback(*args, **kwargs)
 File "/usr/lib/python2.7/site-packages/click-7.0_dev-py2.7.egg/click/decorators.py", line 64, in new_func
   return ctx.invoke(f, obj, *args[1:], **kwargs)
 File "/usr/lib/python2.7/site-packages/click-7.0_dev-py2.7.egg/click/core.py", line 535, in invoke
   return callback(*args, **kwargs)
 File "/usr/lib/python2.7/site-packages/SoftLayer-5.2.0-py2.7.egg/SoftLayer/CLI/config/setup.py", line 62, in cli
   'timeout': timeout})))
 File "/usr/lib/python2.7/site-packages/SoftLayer-5.2.0-py2.7.egg/SoftLayer/CLI/environment.py", line 51, in fmt
   return formatting.format_output(output, fmt=self.format)
 File "/usr/lib/python2.7/site-packages/SoftLayer-5.2.0-py2.7.egg/SoftLayer/CLI/formatting.py", line 38, in format_output
   return str(format_prettytable(data))
 File "/usr/lib/python2.7/site-packages/SoftLayer-5.2.0-py2.7.egg/SoftLayer/CLI/formatting.py", line 83, in format_prettytable
   ptable.hrules = prettytable.FRAME
AttributeError: 'module' object has no attribute 'FRAME'

### Environment Information
Operating System: RHEL 7.2 (Maipo)

softlayer-python version (`slcli --version`): slcli (SoftLayer Command-line), version 5.2.0

**Comment by sudorandom** [comment]
What version of prettytable do you have installed? You can get that by running this command:

```
pip show prettytable
```

Or this (if you don't have pip):
```
ls -l /usr/lib/python2.7/site-packages | grep -i prettytable
```

**Comment by sudorandom** [comment]
Hrm, it looks like you might not have the 'official' prettytable library... instead, it looks like you have this fork of it: https://github.com/kxxoling/PTable. They apparantly did maintain backwards compatibility with prettytable and have used the same name for the module. I'm not sure what the right thing to do here is. Currently, if you want `slcli` to work, you're going to have to uninstall `ptable` (`pip uninstall ptable`) and install `prettytable` (`pip install prettytable`).

**Comment by sotnickd** [comment]
Ahh, that must have been it. Unfortunately I've been working on this from a
host which has no direct Internet access, so pip hasn't been a viable
option.

You can close this bug/issue. Thanks for the response!

**Comment by sudorandom** [comment]
@sotnickd no problem!
