### ISSUE TITLE
Not able to list object-storage endpoints

### ISSUE THREAD

**Issue by bonifaido** [softlayer/softlayer-python#793]
### Expected Behavior
```$ slcli object-storage endpoints```
See the list of object-storage endpoints

### Actual Behavior
```$ slcli object-storage endpoints```
```
An unexpected error has occured:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/CLI/core.py", line 163, in main
    cli.main(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/CLI/object_storage/list_endpoints.py", line 17, in cli
    endpoints = mgr.list_endpoints()
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/managers/object_storage.py", line 48, in list_endpoints
    filter=_filter)['storageNodes']:
TypeError: string indices must be integers, not str

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues
```

### Environment Information
Operating System: OSX 10.12.2 (16C67)
softlayer-python version (`slcli --version`): slcli (SoftLayer Command-line), version 5.2.1

**Comment by camporter** [comment]
Have #802 opened to fix this.

**Comment by allmightyspiff** [comment]
This should be working now.
```
$ slcli object-storage endpoints
:............:......................................................:.................................................................:
: datacenter :                        public                        :                             private                             :
:............:......................................................:.................................................................:
:   hkg02    : https://hkg02.objectstorage.softlayer.net/auth/v1.0/ : https://hkg02.objectstorage.service.networklayer.com/auth/v1.0/ :
:   syd01    : https://syd01.objectstorage.softlayer.net/auth/v1.0/ : https://syd01.objectstorage.service.networklayer.com/auth/v1.0/ :
:   dal05    : https://dal05.objectstorage.softlayer.net/auth/v1.0/ : https://dal05.objectstorage.service.networklayer.com/auth/v1.0/ :
:   ams01    : https://ams01.objectstorage.softlayer.net/auth/v1.0/ : https://ams01.objectstorage.service.networklayer.com/auth/v1.0/ :
:   che01    : https://che01.objectstorage.softlayer.net/auth/v1.0/ : https://che01.objectstorage.service.networklayer.com/auth/v1.0/ :
:   lon02    : https://lon02.objectstorage.softlayer.net/auth/v1.0/ : https://lon02.objectstorage.service.networklayer.com/auth/v1.0/ :
:   mex01    : https://mex01.objectstorage.softlayer.net/auth/v1.0/ : https://mex01.objectstorage.service.networklayer.com/auth/v1.0/ :
:   sao01    : https://sao01.objectstorage.softlayer.net/auth/v1.0/ : https://sao01.objectstorage.service.networklayer.com/auth/v1.0/ :
:   mel01    : https://mel01.objectstorage.softlayer.net/auth/v1.0/ : https://mel01.objectstorage.service.networklayer.com/auth/v1.0/ :
:   par01    : https://par01.objectstorage.softlayer.net/auth/v1.0/ : https://par01.objectstorage.service.networklayer.com/auth/v1.0/ :
:   sjc01    : https://sjc01.objectstorage.softlayer.net/auth/v1.0/ : https://sjc01.objectstorage.service.networklayer.com/auth/v1.0/ :
:   tor01    : https://tor01.objectstorage.softlayer.net/auth/v1.0/ : https://tor01.objectstorage.service.networklayer.com/auth/v1.0/ :
:   mon01    : https://mon01.objectstorage.softlayer.net/auth/v1.0/ : https://mon01.objectstorage.service.networklayer.com/auth/v1.0/ :
:   fra02    : https://fra02.objectstorage.softlayer.net/auth/v1.0/ : https://fra02.objectstorage.service.networklayer.com/auth/v1.0/ :
:   mil01    : https://mil01.objectstorage.softlayer.net/auth/v1.0/ : https://mil01.objectstorage.service.networklayer.com/auth/v1.0/ :
:   tok02    : https://tok02.objectstorage.softlayer.net/auth/v1.0/ : https://tok02.objectstorage.service.networklayer.com/auth/v1.0/ :
:   sng01    : https://sng01.objectstorage.softlayer.net/auth/v1.0/ : https://sng01.objectstorage.service.networklayer.com/auth/v1.0/ :
:............:......................................................:.................................................................:
```
