### ISSUE TITLE
create vsi from image_id failed for blockDevices

### ISSUE THREAD

**Issue by bali2016** [softlayer/softlayer-python#804]
**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**

### Expected Behavior
The vis can be successfully created from image_id.

### Actual Behavior
The VSI can not be created from image_id:
I have a image templete and want to create a vsi by the python API. It always fails with this reason: "Invalid value provided for 'blockDevices'. Block devices may not be provided when using an image template."

```
new_vsi = {
    'domain': u'test01.labs.sftlyr.ws',
    'hostname': u'minion05',
    'datacenter': u'hkg02',
    'dedicated': False,
    'private': False,
    'cpus': 1,
    'image_id' : 1498971,
    #'os_code' : u'UBUNTU_LATEST',
    'hourly': True,
    'ssh_keys': [],
    'disks': ('100','25'),
    'local_disk': True,
    'memory': 1024,
    'tags': 'test, pleaseCancel'
}
....
vsi_mgr = SoftLayer.VSManager(client)
>>> waf = vsi_mgr.create_instance(**new_vsi)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/managers/vs.py", line 544, in create_instance
    inst = self.guest.createObject(self._generate_create_dict(**kwargs))
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/API.py", line 392, in call_handler
    return self(name, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/API.py", line 360, in call
    return self.client.call(self.name, name, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/API.py", line 263, in call
    return self.transport(request)
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/transports.py", line 195, in __call__
    raise _ex(ex.faultCode, ex.faultString)
SoftLayer.exceptions.SoftLayerAPIError: SoftLayerAPIError(SoftLayer_Exception_InvalidValue): Invalid value provided for 'blockDevices'. Block devices may not be provided when using an image template.
```

```
 #slcli image detail 1498971
:....................:......................................:
:               name : value                                :
:....................:......................................:
:                 id : 1498971                              :
:  global_identifier : d77202f1-daa5-41a7-83bd-2689e843897f :
:               name : waf-modsecurity                      :
:             status : Active                               :
: active_transaction : -                                    :
:            account : 323716                               :
:         visibility : Private                              :
:               type : System                               :
:               flex : False                                :
:               note : None                                 :
:            created : 2017-02-13T16:15:46+08:00            :
:         disk_space : 3.11G                                :
:        datacenters : dal05,dal06,hkg02                    :
:....................:......................................:
```
### Environment Information
Operating System: CentOS 7
softlayer-python version (`slcli --version`):
```
# slcli --version
slcli (SoftLayer Command-line), version 5.2.1
```

**Comment by allmightyspiff** [comment]
When using an image template, the block devices are based on the image template, you cannot specify them during order. This is the same as in the control portal.

https://softlayer.github.io/python/create_server_from_template/

**Comment by bali2016** [comment]
@allmightyspiff Thanks for your reply, when I removed disks and localDisks variables, it shows another error message:

```
new_vsi = {
    'domain': u'test01.labs.sftlyr.ws',
    'hostname': u'minion05',
    'datacenter': u'hkg02',
    'dedicated': False,
    'private': False,
    'cpus': 1,
    'image_id' : 1498971,
    #'os_code' : u'UBUNTU_LATEST',
    'hourly': True,
    'ssh_keys': [],
    #'disks': ('100','25'),
    #'local_disk': True,
    'memory': 1024,
    'tags': 'test, pleaseCancel'
}
....
vsi_mgr = SoftLayer.VSManager(client)
>>> waf = vsi_mgr.create_instance(**new_vsi)
Traceback (most recent call last):
  File "deploy.py", line 44, in <module>
    deploy_waf(cpus=2, memory=2048, hostname="test-waf.sl.com",domain="waf.test.domain")
  File "deploy.py", line 38, in deploy_waf
    waf = vsi_mgr.create_instance(**new_waf)
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/managers/vs.py", line 544, in create_instance
    inst = self.guest.createObject(self._generate_create_dict(**kwargs))
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/API.py", line 392, in call_handler
    return self(name, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/API.py", line 360, in call
    return self.client.call(self.name, name, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/API.py", line 263, in call
    return self.transport(request)
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/transports.py", line 195, in __call__
    raise _ex(ex.faultCode, ex.faultString)
SoftLayer.exceptions.SoftLayerAPIError: SoftLayerAPIError(SoftLayer_Exception_InvalidValue): Invalid value provided for 'blockDeviceTemplateGroup.globalIdentifier'. A valid global identifier is required for a template.
```

**Comment by allmightyspiff** [comment]
You need to supply the GUID for the image, not the ID. I'll have to correct the documentation for that.

You can get the GUID with "slcli image detail <image_id>"
```
$ slcli image detail 1505785
:....................:.....................................................:
:               name : value                                               :
:....................:.....................................................:
:                 id : 1505785                                             :
:  global_identifier : 9ad2e621-fd92-417a-a3df-92730aebcaa0                :
:               name : 100GB - Ubuntu / Ubuntu / 16.04-64 Minimal for VSI  :
:             status : Internal                                            :
: active_transaction : -                                                   :
:            account : 208938                                              :
:         visibility : Public                                              :
:               type : System                                              :
:               flex : False                                               :
:               note : Public Stock Image Template                         :
:                    : 100GB - Ubuntu / Ubuntu / 16.04-64 Minimal for VSI  :
:                    : 16.04 Ubuntu 16.04.1 LTS                            :
:                    : 4.4.0-53-generic                                    :
:            created : 2017-02-20T09:07:00-06:00                           :
:         disk_space : 1.04G                                               :
:        datacenters : ams01,dal01                                         :
:....................:.....................................................:
```

Here is an example on how to use the SoftLayer_Virtual_Guest::createObject method directly, which is largely what the VSImanager does.
```
client = SoftLayer.Client()

guest = {}
guest['startCpus'] = 1
guest['maxMemory'] = 1024
guest['localDiskFlag'] = False
guest['hostname'] = "salt-masterv13-1"
guest['domain'] =  "bdalab-1.lablayer.info"
guest['hourlyBillingFlag'] = True
guest['datacenter'] = {}
guest['datacenter']['name'] = 'sjc01'
#v13
guest['blockDeviceTemplateGroup'] = {'globalIdentifier': "6c64f59a-edeb-4ba4-b992-111111111111"}
result = client['Virtual_Guest'].createObject(guest)
print "Added server id: %s  ( %s )" % (result['id'],result['fullyQualifiedDomainName']) 
```

In the CLI

```
sl vs create --datacenter=dal09  --hostname=minionTest --domain=lablayer.info --billing=hourly --key=Christophers-MacBook-Pro.local-key --cpu=2 --memory=2 --image=05c8ee79-66d1-4127-9907-111111111111
```

I hope this helps.

**Comment by bali2016** [comment]
Thanks, now it works.

```
new_vsi = {
    'domain': u'test01.labs.sftlyr.ws',
    'hostname': u'minion05',
    'datacenter': u'hkg02',
    'dedicated': False,
    'private': False,
    'cpus': 1,
    'image_id' : 'd77202f1-daa5-41a7-83bd-2689e843897f',
    #'os_code' : u'UBUNTU_LATEST',
    'hourly': True,
    'ssh_keys': [],
    #'disks': ('100','25'),
    #'local_disk': True,
    'memory': 1024,
    'tags': 'test, pleaseCancel'
}
...
>>>vsi_mgr = SoftLayer.VSManager(client)
>>> waf = vsi_mgr.create_instance(**new_vsi)
 {'domain': 'waf.test.domain', 'maxMemory': 2048, 'uuid': '86679862-a9cd-47f2-b3ef-f1cbdbb62c09', 'maxCpu': 2, 'metricPollDate': '', 'createDate': '2017-02-25T09:27:40+08:00', 'hostname': 'test-waf.sl.com', 'startCpus': 2, 'lastPowerStateId': '', 'lastVerifiedDate': '', 'statusId': 1001, 'globalIdentifier': 'c0b630b2-6317-441b-b118-05a786477b8c', 'provisionDate': '', 'maxCpuUnits': 'CORE', 'modifyDate': '', 'accountId': 323716, 'id': 28773977, 'fullyQualifiedDomainName': 'test-waf.sl.com.waf.test.domain'}
```

**Comment by PedroMVM** [comment]
> You need to supply the GUID for the image, not the ID. I'll have to correct the documentation for that.

Could you please update [documentation](http://softlayer-python.readthedocs.io/en/latest/api/managers/vs.html)? I had the same issues.

**Comment by allmightyspiff** [comment]
I've updated the docs to mention GUID for image templates
