### ISSUE TITLE
i create order using quote in api call i got error

### ISSUE THREAD

**Issue by RobertRajcool** [softlayer/softlayer-python#808]
client = SoftLayer.Client(username='username', api_key='apikey')
first get the order container from quote:
container = client['Billing_Order_Quote'].getRecalculatedOrderContainer(id=quoteId)
then i place the order:
order=client['Product_Order'].placeOrder(container)
i got error like this;
Traceback (most recent call last):
  File "/home/robert/Projects/ServerProjects/Redington/trunk/django/trunkenv/lib/python3.4/site-packages/SoftLayer/transports.py", line 173, in __call__
    result = utils.xmlrpc_client.loads(resp.content)[0][0]
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1003, in loads
    return u.close(), u.getmethodname()
  File "/usr/lib/python3.4/xmlrpc/client.py", line 657, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault SoftLayer_Exception_Order_InvalidData: 'Invalid data on the order for property: virtualGuests. Hostname and domain are not set properly.'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/robert/Projects/ServerProjects/Redington/trunk/django/trunkenv/lib/python3.4/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-57-2414875a0ca5>", line 1, in <module>
    redingtonclient['Product_Order'].placeOrder(container)
  File "/home/robert/Projects/ServerProjects/Redington/trunk/django/trunkenv/lib/python3.4/site-packages/SoftLayer/API.py", line 392, in call_handler
    return self(name, *args, **kwargs)
  File "/home/robert/Projects/ServerProjects/Redington/trunk/django/trunkenv/lib/python3.4/site-packages/SoftLayer/API.py", line 360, in call
    return self.client.call(self.name, name, *args, **kwargs)
  File "/home/robert/Projects/ServerProjects/Redington/trunk/django/trunkenv/lib/python3.4/site-packages/SoftLayer/API.py", line 263, in call
    return self.transport(request)
  File "/home/robert/Projects/ServerProjects/Redington/trunk/django/trunkenv/lib/python3.4/site-packages/SoftLayer/transports.py", line 195, in __call__
    raise _ex(ex.faultCode, ex.faultString)
SoftLayer.exceptions.SoftLayerAPIError: SoftLayerAPIError(SoftLayer_Exception_Order_InvalidData): Invalid data on the order for property: virtualGuests. Hostname and domain are not set properly.

**Comment by allmightyspiff** [comment]
You need to set the hostname and domain name before placing an order.

https://softlayer.github.io/python/order_quote/
https://softlayer.github.io/python/order_quote_advanced/
