### ISSUE TITLE
'slcli file volume-list' fails

### ISSUE THREAD

**Issue by hrishikesh988** [softlayer/softlayer-python#812]
# slcli --version
slcli (SoftLayer Command-line), version 5.2.3

I am getting following error when I run "slcli file volume-list"

An unexpected error has occured:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/SoftLayer/CLI/core.py", line 163, in main
    cli.main(**kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/SoftLayer/CLI/file/list.py", line 69, in cli
    mask=columns.mask())
  File "/usr/lib64/python2.7/site-packages/SoftLayer/managers/file.py", line 63, in list_file_volumes
    pp(kwargs['filter'])
NameError: global name 'pp' is not defined

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues

**Comment by allmightyspiff** [comment]
Thanks I'll look into this.

**Comment by allmightyspiff** [comment]
This should work now
```bash
$ slcli --version
slcli (SoftLayer Command-line), version 5.2.4
$ slcli file volume-list
:..........:.......................:............:..............:.............:............:.......................................:.....................:....................................................................:
:    id    :        username       : datacenter : storage_type : capacity_gb : bytes_used :                ip_addr                : active_transactions :                             mount_addr                             :
:..........:.......................:............:..............:.............:............:.......................................:.....................:....................................................................:
[omitted]
:..........:.......................:............:..............:.............:............:.......................................:.....................:....................................................................:
```
