### ISSUE TITLE
slcli block volume-detail fails

### ISSUE THREAD

**Issue by tobilarscheid** [softlayer/softlayer-python#820]
### Expected Behavior

Calling `slcli block volume-detail ##numeric-volume-id##` should print details

### Actual Behavior

```shell
 slcli block volume-detail ##numeric-volume-id##
An unexpected error has occured:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/CLI/core.py", line 163, in main
    cli.main(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/CLI/block/detail.py", line 37, in cli
    block_volume['storageTierLevel']['description'],
TypeError: string indices must be integers, not str

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues

```

When I enter an invalid ID (e.g. `slcli block volume-detail abc`) the tool returns `SoftLayerAPIError(SOAP-ENV:Server): Internal Error`

### Environment Information
Operating System: macOS 10.12.4
softlayer-python version (`slcli --version`): `slcli (SoftLayer Command-line), version 5.2.4`

**Comment by allmightyspiff** [comment]
https://softlayer.github.io/release_notes/20170503/
I'll have a new version out shortly to address that. 

Thanks for opening this issue.

**Comment by allmightyspiff** [comment]
https://github.com/softlayer/softlayer-python/releases/tag/v5.2.5 should fix this now.
