### ISSUE TITLE
Unable to list globalips

### ISSUE THREAD

**Issue by tomwganem** [softlayer/softlayer-python#825]
### Expected Behavior
That I can list globalips

### Actual Behavior

```bash
$ slcli globalip list
An unexpected error has occured:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/CLI/core.py", line 163, in main
    cli.main(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/CLI/globalip/list.py", line 47, in cli
    ip_address['ipAddress']['ipAddress'],
KeyError: 'ipAddress'

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues

```
### Environment Information
Operating System: MAC OS 10.12.4
softlayer-python version (`slcli --version`): slcli (SoftLayer Command-line), version 5.2.4

This may be a problem on my softlayer account. I created three globalips today, but an hour later, just out of the blue, two of them are gone. The webui indicates I only have one global ip now (I've created a ticket in softlayer for this problem)

If I use credentials from a different account, I can list global ips no problem

```bash
$ slcli -C ~/.softlayer-prod globalip list
:....:....:..........:........:
: id : ip : assigned : target :
:....:....:..........:........:
:....:....:..........:........:
```

**Comment by ScottieD** [comment]
I am not able to replicate the issue. The tests you are running, are they both in the same python environment?

**Comment by allmightyspiff** [comment]
This should work at least as of 5.8.9. If your still having problems do let us know, and I'll check again. Won't take me 3 years to respond this time :)

```
$ slcli --format=table globalip list
:........:................:..........:................:
:   id   :       ip       : assigned :     target     :
:........:................:..........:................:
: 163542 : 108.168.254.54 :    No    :      None      :
:........:................:..........:................:
```
