### ISSUE TITLE
CLI throwing error when running bandwidth report

### ISSUE THREAD

**Issue by greyhoundforty** [softlayer/softlayer-python#831]
### Expected Behavior
Get a report of the bandwidth from all servers, vsis and bandwidth pools

### Actual Behavior

```
ryan@tycho ~ » slcli report bandwidth
Generating bandwidth report for 2017-05-12 00:00:00 to 2017-06-11 00:00:00
Calculating for bandwidth pools  [####################################]  100%
Calculating for virtual  [#######-----------------------------]   21%  0d 00:00:52
An unexpected error has occured:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/CLI/core.py", line 163, in main
    cli.main(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/CLI/report/bandwidth.py", line 214, in cli
    _get_hardware_bandwidth(env, start, end)):
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/CLI/report/bandwidth.py", line 164, in _get_virtual_bandwidth
    id=instance['metricTrackingObjectId'],
KeyError: 'metricTrackingObjectId'

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues
```

### Environment Information

```
ryan@tycho ~ » mac info
sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.5
BuildVersion:	16F73

ryan@tycho ~ » slcli --version
slcli (SoftLayer Command-line), version 5.2.6
```

**Comment by jkapusi** [comment]
Is there a solution to this problem?
