### ISSUE TITLE
'slcli hardware detail 11744' generates traceback

### ISSUE THREAD

**Issue by briancn** [softlayer/softlayer-python#847]
**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**

'slcli hardware detail 11744' command causes error/traceback

### Actual Behavior
An unexpected error has occured:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/SoftLayer-5.2.8-py2.7.egg/SoftLayer/CLI/core.py", line 163, in main
    cli.main(**kwargs)
  File "/Library/Python/2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click-6.7-py2.7.egg/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/Library/Python/2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/SoftLayer-5.2.8-py2.7.egg/SoftLayer/CLI/hardware/detail.py", line 46, in cli
    table.add_row(['memory', formatting.gb(result['memoryCapacity'])])
  File "/Library/Python/2.7/site-packages/SoftLayer-5.2.8-py2.7.egg/SoftLayer/CLI/formatting.py", line 131, in gb
    return FormattedItem(int(float(gigabytes)) * 1024,
TypeError: float() argument must be a string or a number

### Environment Information
Operating System:
Mac 10.12.5 (16F2073)

softlayer-python version (`slcli --version`):
slcli (SoftLayer Command-line), version 5.2.8

**Comment by sergiocarlosmorales** [comment]
Thanks Brian,
How did you get the hardware ID 11744?
That's the ID that comes back when you query for the front-end router in SEA01, and the SLCLI hardware module is mostly designed to deal with servers.. (Although the underlying service SoftLayer_Hardware covers both).
Just trying to understand your use case a little bit better.

**Comment by briancn** [comment]
Hi Sergio,


I don't remember how I got the id.  I think I may have gotten it using my internal portal.  (I am a contractor doing work for SoftLayer.). It is not that I really care about that particular item, it just seems there should be some input validation that generates a more user-friendly error (instead of a traceback).

-Brian
________________________________

**Comment by sergiocarlosmorales** [comment]
Thanks for the info, I've submitted a pull req https://github.com/softlayer/softlayer-python/pull/849 to show the available information from the hardware and not completely blow up when missing the memory key.

**Comment by sergiocarlosmorales** [comment]
Merged & released, thanks for reporting it!
