### ISSUE TITLE
slcli caused TransportError(0): [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)

### ISSUE THREAD

**Issue by MarikoTagawa** [softlayer/softlayer-python#857]
slcli command worked perfectly on my Mac until yesterday. 
Since this morning it returns below error.
I have 2 MACs and on both of them, I got the same error.

$ slcli vm list
TransportError(0): [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)

I searched the internet and found this suggestion.
>Install requests with extra security packages using: pip install requests[security]. 

So I installed it.
Then below error occurred.
slcli vm list
An unexpected error has occured:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/SoftLayer-5.2.0-py2.7.egg/SoftLayer/CLI/core.py", line 163, in main
    cli.main(**kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/decorators.py", line 63, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/SoftLayer-5.2.0-py2.7.egg/SoftLayer/CLI/virt/list.py", line 80, in cli
    mask=columns.mask())
  File "/Library/Python/2.7/site-packages/SoftLayer-5.2.0-py2.7.egg/SoftLayer/managers/vs.py", line 155, in list_instances
    return func(**kwargs)
  File "/Library/Python/2.7/site-packages/SoftLayer-5.2.0-py2.7.egg/SoftLayer/API.py", line 392, in call_handler
    return self(name, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/SoftLayer-5.2.0-py2.7.egg/SoftLayer/API.py", line 360, in call
    return self.client.call(self.name, name, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/SoftLayer-5.2.0-py2.7.egg/SoftLayer/API.py", line 263, in call
    return self.transport(request)
  File "/Library/Python/2.7/site-packages/SoftLayer-5.2.0-py2.7.egg/SoftLayer/transports.py", line 331, in __call__
    result = self.transport(call)
  File "/Library/Python/2.7/site-packages/SoftLayer-5.2.0-py2.7.egg/SoftLayer/transports.py", line 168, in __call__
    proxies=_proxies_dict(self.proxy))
  File "/Library/Python/2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/Library/Python/2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/Library/Python/2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 344, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/Library/Python/2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 314, in _raise_timeout
    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
TypeError: __str__ returned non-string (type Error)

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues

### Expected Behavior

slcli worked and return response.

### Actual Behavior

TransportError(0): [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)

### Environment Information
Operating System:MAX OS 10.12.3
softlayer-python version (`slcli --version`):
slcli (SoftLayer Command-line), version 5.2.0

**Comment by allmightyspiff** [comment]
is this still a problem? Might have just been a problem on the API endpoint side. 

If it is still a problem, please try updating to 5.2.13
and post the result of your call with 
```slcli -v -v -v  vs list```
the output will contain your API key, so be sure to remove that before posting of course.

Thanks.

**Comment by MarikoTagawa** [comment]
Hi,
>is this still a problem? Might have just been a problem on the API endpoint side.

Yes, the problem happened only on that day. My colleagues got the same error. So it must be a problem on the API endpoint side.
I'm closing this issue.

**Comment by sergiocarlosmorales** [comment]
For documentation purposes, this was caused by SoftLayer UIP 46102597.
TLS ciphers related, it exposed the inability of the SLCLI client to handle non TLS 1.0 connections, so we should look at adding support for it eventually.
