### ISSUE TITLE
unble to setup softlayer credentials by using slcli 

### ISSUE THREAD

**Issue by cindyCLJ** [softlayer/softlayer-python#871]
**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**

### Actual Behavior
cindy@ansib1:~$ slcli setup
Username []: ljchensh_571879
API Key or Password []:
Endpoint (public|private|custom) [public]: https://api.softlayer.com/xmlrpc/v3.1
Timeout [0]: 0
An unexpected error has occured:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/SoftLayer/CLI/core.py", line 173, in main
    cli.main(**kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/SoftLayer/CLI/config/setup.py", line 49, in cli
    username, secret, endpoint_url, timeout = get_user_input(env)
  File "/usr/lib/python2.7/dist-packages/SoftLayer/CLI/config/setup.py", line 122, in get_user_input
    return username, secret, endpoint_url, timeout
UnboundLocalError: local variable 'endpoint_url' referenced before assignment
### Environment Information
Operating System: ubuntu 16.04
softlayer-python version (`slcli --version`):
slcli (SoftLayer Command-line), version 4.1.1

**Comment by dpickle2** [comment]
I will try to see if there is a way to handle this error more elegantly.
However, as a temporary fix, please try inputting the word, "public", instead of the actual public endpoint URL, "https://api.softlayer.com/xmlrpc/v3.1". I think this might allow you to complete the setup process normally.

**Comment by cindyCLJ** [comment]
Thanks . It can be completed if inputting the word "public".

**Comment by camporter** [comment]
Created a PR to avoid an error being presented.

**Comment by allmightyspiff** [comment]
This should be fixed in #881, if not let me know.
