### ISSUE TITLE
exception error when cancelling block storage via CLI

### ISSUE THREAD

**Issue by engrmg** [softlayer/softlayer-python#880]
**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**

SLCLI command:

slcli block volume-cancel --immediate <volume id>

### Expected Behavior
Some sort of response acknowledging the cancelling request.

### Actual Behavior
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/SoftLayer/CLI/core.py", line 163, in main
    cli.main(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/SoftLayer/CLI/block/cancel.py", line 29, in cli
    reason, immediate)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/SoftLayer/managers/block.py", line 472, in cancel_block_volume
    billing_item_id = block_volume['billingItem']['id']
KeyError: 'billingItem'

### Environment Information
Operating System: mac os
softlayer-python version (`slcli --version`):  version 5.2.14

**Comment by sergiocarlosmorales** [comment]
Hey Miguel, thanks for reporting.
The most likely cause for a volume to not have a billing item (causing this key failure) its because the billing item has already been cancelled (either immediate or in a future date).
That being said, this needs to be handled gracefully for sure, but wanted to share the most common cause for 'missing' billing item on a volume.

**Comment by allmightyspiff** [comment]
This will be fixed in the next release.
