### ISSUE TITLE
setTags on create instance can timeout

### ISSUE THREAD

**Issue by allmightyspiff** [softlayer/softlayer-python#884]
add retry logic to setTags to prevent RateLimit exceptions from breaking everything.

```
SoftLayerAPIError: SoftLayerAPIError(SoftLayer_Exception_WebService_RateLimitExceeded): Rate limit of 50 requests for every 1 second(s) exceeded.
[WARNING] 2017-10-05 00:00:41,435 vsprovision (Thread-14 ) Hit SoftLayerAPIError(SoftLayer_Exception_WebService_RateLimitExceeded): Rate limit of 50 requests for every 1 second(s) exceeded. Attempts Counter 1 took 40 sec at 1507186841.44
Traceback (most recent call last):
  File "/git/continuous_provision/src/lib/vsprovision.py", line 166, in process
    vsi = mgr.create_instance(**new_vsi)
  File "/usr/lib64/python2.7/site-packages/SoftLayer/managers/vs.py", line 587, in create_instance
    self.guest.setTags(tags, id=inst['id'])
  File "/usr/lib64/python2.7/site-packages/SoftLayer/API.py", line 392, in call_handler
    return self(name, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/SoftLayer/API.py", line 360, in call
    return self.client.call(self.name, name, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/SoftLayer/API.py", line 263, in call
    return self.transport(request)
  File "/usr/lib64/python2.7/site-packages/SoftLayer/transports.py", line 195, in __call__
    raise _ex(ex.faultCode, ex.faultString)
```

**Comment by allmightyspiff** [comment]
fixed in #895
