### ISSUE TITLE
Fail to cancel file storage volume using slcli

### ISSUE THREAD

**Issue by cindyCLJ** [softlayer/softlayer-python#908]
**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**
cindy@ansib1:~$ slcli file volume-cancel 31634435 --immediate
This action cannot be undone! Type "31634435" or press Enter to abort: 31634435
An unexpected error has occured:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/SoftLayer/CLI/core.py", line 163, in main
    cli.main(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/SoftLayer/CLI/file/cancel.py", line 29, in cli
    reason, immediate)
  File "/usr/local/lib/python2.7/dist-packages/SoftLayer/managers/file.py", line 483, in cancel_file_volume
    billing_item_id = file_volume['billingItem']['id']
KeyError: 'billingItem'

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues
### Environment Information
Operating System:
ubuntu 16.04
softlayer-python version (`slcli --version`):

slcli (SoftLayer Command-line), version 5.2.13

**Comment by allmightyspiff** [comment]
This has been reported in #880  already, but thanks for opening it. 

having this command fail more gracefully is on my todo list.
