### ISSUE TITLE
Error when using sshkey add

### ISSUE THREAD

**Issue by VanBantam** [softlayer/softlayer-python#925]
### When running the command:
`slcli sshkey add AAAAB3NzaC1yc2EAAAADAQABAAABAQC6doGzVqgthI8mfEtOB5UCRRKTyn7s+3xOUHkEDif5Li8bju2ynQXlvR+KC+RKJ4G4BX1d/1qHFsXM/l7Kji5wuFey072IWcf0LYOUCffrQI/mMThxXQAhUBeyXMwRwRGV/MbqcEaTkg2aA4d3h3SzVjP3EKOy/VGWLMBeQnL9epx5sdNwpgOlJDfI2bezEjS4TzuJXazxKUPGGiBqT4iD/iOuP8dU+yqcudGzVkENjYoXT5XDP0kvYLhvKXfnoixINpS8yakgITzUAkUAXaocsyHPVwkRdekgjQDD0OGgwDN6DImv2JD1FscUGVX6F+PmTY/n+cCgfNFw50XJ5gBx`

### I get the following error:
```
An unexpected error has occured:
Traceback (most recent call last):
  File "//anaconda/lib/python3.5/site-packages/SoftLayer/CLI/core.py", line 163, in main
    cli.main(**kwargs)
  File "//anaconda/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "//anaconda/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "//anaconda/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "//anaconda/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "//anaconda/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "//anaconda/lib/python3.5/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "//anaconda/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "//anaconda/lib/python3.5/site-packages/SoftLayer/CLI/sshkey/add.py", line 25, in cli
    key_file = open(path.expanduser(in_file), 'rU')
  File "//anaconda/lib/python3.5/posixpath.py", line 229, in expanduser
    if not path.startswith(tilde):
AttributeError: 'NoneType' object has no attribute 'startswith'

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues
```

### Environment Information
Operating System: OS X 10.12.6
softlayer-python version (`slcli --version`): slcli (SoftLayer Command-line), version 5.3.2

This issue relates to:
https://github.com/softlayer/softlayer-python/issues/788

**Comment by VanBantam** [comment]
Issue should be closed: another instance of not reading the help file more carefully.

```
slcli sshkey add --help
Usage: slcli sshkey add [OPTIONS] LABEL

  Add a new SSH key.

Options:
  **-f, --in-file PATH  The id_rsa.pub file to import for this key**
  **-k, --key TEXT      The actual SSH key**
  --note TEXT         Extra note that will be associated with key
  -h, --help          Show this message and exit.
```

**Comment by camporter** [comment]
Wrote PR #926 to make it more obvious that either the key argument or key file is needed, to avoid the issue shown above where the key file tries to be opened when it is not actually set.
