### ISSUE TITLE
VS Manager cancel_instance() method fails

### ISSUE THREAD

**Issue by tianhw2006** [softlayer/softlayer-python#947]
**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**

### Expected Behavior
Call this method in my codes, and expect the instance of virtual service can be removed. The credentials and instance_id are correct.

### Actual Behavior
Exception is thrown as follows:
```  
  File "test.py", line 48, in cancel_vm
    self.vs_manager.cancel_instance(vm_id)
  File "/Library/Python/2.7/site-packages/SoftLayer/managers/vs.py", line 263, in cancel_instance
    return self.guest.deleteObject(id=instance_id)
  File "/Library/Python/2.7/site-packages/SoftLayer/API.py", line 390, in call_handler
    return self(name, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/SoftLayer/API.py", line 358, in call
    return self.client.call(self.name, name, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/SoftLayer/API.py", line 261, in call
    return self.transport(request)
  File "/Library/Python/2.7/site-packages/SoftLayer/transports.py", line 332, in __call__
    message)
SoftLayer.exceptions.SoftLayerAPIError: SoftLayerAPIError(404): Service does not exist
```

### Environment Information
Operating System: Mac
python version: 2.7.10
softlayer-python version (`slcli --version`): 5.4.2

**Comment by allmightyspiff** [comment]
Hey, I'm not able to reproduce this error. My guess is that this might have been a temporary issue with the SoftLayer API itself.

```bash
$ python cancel.py
True
$ python cancel.py
Traceback (most recent call last):
  File "/Users/christopher/Code/softlayer-python/SoftLayer/transports.py", line 193, in __call__
    result = utils.xmlrpc_client.loads(resp.content)[0][0]
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xmlrpc/client.py", line 1021, in loads
    return u.close(), u.getmethodname()
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xmlrpc/client.py", line 656, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault SoftLayer_Exception_NotFound: 'A billing item is required to process a cancellation.'>
```

cancel.py
```python
import SoftLayer
from pprint import pprint as pp

vsi_id = 50119675

client = SoftLayer.Client()
vsmgr = SoftLayer.VSManager(client)
result = vsmgr.cancel_instance(vsi_id)
pp(result)
```


Can you try your script again and see if it is still giving that error?

**Comment by tianhw2006** [comment]
Hey, thank you so much. It turns out that I set wrong endpoint_url in system variable.
