### ISSUE TITLE
SoftLayer_Exception_Order_MissingCategory: 

### ISSUE THREAD

**Issue by AnishAnil** [softlayer/softlayer-python#952]
### Expected Behavior
Was expected the Vyatta softlayer instance review could have happened
### Actual Behavior
Ended up with the below error:

```
python3 softlayervyatta.py 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/SoftLayer/transports.py", line 193, in __call__
    result = utils.xmlrpc_client.loads(resp.content)[0][0]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xmlrpc/client.py", line 1021, in loads
    return u.close(), u.getmethodname()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xmlrpc/client.py", line 656, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault SoftLayer_Exception_Order_MissingCategory: 'Order is missing the following categories: Operating System, RAM, Disk Controller, First Hard Drive, Public Bandwidth, Uplink Port Speeds, Remote Management, Primary IP Addresses, Primary IPv6 Addresses, Monitoring, Notification, Response, VPN Management - Private Network, Vulnerability Assessments & Management.'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "softlayervyatta.py", line 62, in <module>
    order = client['Product_Order'].verifyOrder(productOrder)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/SoftLayer/API.py", line 390, in call_handler
    return self(name, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/SoftLayer/API.py", line 358, in call
    return self.client.call(self.name, name, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/SoftLayer/API.py", line 261, in call
    return self.transport(request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/SoftLayer/transports.py", line 215, in __call__
    raise _ex(ex.faultCode, ex.faultString)
SoftLayer.exceptions.SoftLayerAPIError: SoftLayerAPIError(SoftLayer_Exception_Order_MissingCategory): Order is missing the following categories: Operating System, RAM, Disk Controller, First Hard Drive, Public Bandwidth, Uplink Port Speeds, Remote Management, Primary IP Addresses, Primary IPv6 Addresses, Monitoring, Notification, Response, VPN Management - Private Network, Vulnerability Assessments & Management.
```

**********
### Environment Information
Operating System:
MAC
softlayer-python version (`slcli --version`):
slcli --version
slcli (SoftLayer Command-line), version 5.4.2
python3 --version
Python 3.6.1

```
# pip3 install softlayer
# sudo slcli config setup
# sudo slcli vs list
#
#
# http://sldn.softlayer.com/article/Python

import SoftLayer
from SoftLayer import utils
import sys
import pprint
import logging


# logging.basicConfig(format='%(levelname)s:%(message)s', level=logging.DEBUG)

logging.debug("Starting up")
pp = pprint.PrettyPrinter(indent=4)
client = SoftLayer.Client(username=1234567890,api_key=1234567890)

productOrder = {'orderContainers': [
        {'hardware':
            [
                {'domain': u'cr02a.dal05.com',
                 'hostname': u'cgallo-vyatta',
                 #Private VLAN 1147 on bcr02a.dal05
                 #Private VLAN 1329 on bcr02a.dal05 Details
                 'primaryBackendNetworkComponent': {'networkVlanId': 292444},
                 #Public VLAN 1651 on fcr02a.dal05 Details
                 #Public VLAN 1425 on fcr02a.dal05
                 'primaryNetworkComponent': {'networkVlanId': 292443}
                }
            ],
            #'location': 138124,
            'packageId': 174,
            'location': 138124,
            #'packageId': 174,
            'prices': [
                {'id': 166847}, {'id': 36044}, {'id': 21010},
                {'id': 876}, {'id': 1267}, {'id': 342},
                {'id': 273}, {'id': 906}, {'id': 21},
                {'id': 17129}, {'id': 55}, {'id': 57},
                {'id': 58}, {'id': 420}, {'id': 418}
            ],
            'quantity': 1
        }
    ]
}

accountClient = client['SoftLayer_Account']
gatewayClient = client['SoftLayer_Network_Gateway']

# gateway = gatewayClient.getObject(id=31882,mask='insideVlans[networkVlan[vlanNumber]]')
gateway = accountClient.getNetworkGateways();

# vlans = accountClient.getNetworkVlans(mask='primaryRouter');

getVlanThing = {'locationId':265592,'packageId':174}
#order = client['Product_Order'].placeOrder(productOrder)
order = client['Product_Order'].verifyOrder(productOrder)
pp.pprint(order);

```

Any help is greatly appreciated

Thank you,
Anish

**Comment by allmightyspiff** [comment]
The latest python client has some ordering helper functions that might work for you. I've documented a few examples on how to order a vyatta with them here:

https://softlayer.github.io/python/orderVyatta/

Hopefully that helps.
