### ISSUE TITLE
Things that don't work with the rest endpoint

### ISSUE THREAD

**Issue by allmightyspiff** [softlayer/softlayer-python#962]
1. locationGroupId == None instead of ''
2. slcli image list  (another example of NOne vs '')
3. slcli vs cancel 
    https://api.softlayer.com:443 "DELETE /rest/v3.1/SoftLayer_Virtual_Guest/53116861/deleteObject.json HTTP/1.1" 404 70

**Comment by allmightyspiff** [comment]
REST doesn't seem to be properly raising exceptions.
### XML-RPC
```bash
 ✘  (py3) ~/Code  slcli  ticket list --closed
SoftLayerAPIError(SOAP-ENV:Server): Internal Error
```

### REST
```bash
 (py3) ~/Code  slcli  ticket list --closed
An unexpected error has occured:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/SoftLayer/CLI/core.py", line 182, in main
    cli.main(**kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/SoftLayer/CLI/ticket/list.py", line 28, in cli
    if ticket.get('assignedUser'):
AttributeError: 'unicode' object has no attribute 'get'

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues
The following snippet should be able to reproduce the error
```
