### ISSUE TITLE
Error in slcli credentials call

### ISSUE THREAD

**Issue by npothen** [softlayer/softlayer-python#981]
**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**

### Expected Behavior
password to be displayed

### Actual Behavior

$ slcli hardware list
:.........:.............:............:................:............:........:
:    id   :   hostname  : primary_ip :   backend_ip   : datacenter : action :
:.........:.............:............:................:............:........:
: 1537051 : ***   :     -   :  -.-.-.-:   dal10    :   -    :
: 1012647 : *** : -.-.-.- :  -.-.-.-:   hou02    :   -    :
: 1000041 : *** : -.-.-.- :  -.-.-.-:   hou02    :   -    :
:  857951 :  *** : -.-.-.- :  -.-.-.-:   hou02    :   -    :
:.........:.............:............:................:............:........:

$ slcli hardware credentials 857951
:..........:..........:
: username : password :
:..........:..........:
:   *****   : ******** :
:..........:..........:

$ slcli hardware credentials 1537051
An unexpected error has occured:
Traceback (most recent call last):
  File "...../lib/python2.7/site-packages/SoftLayer/CLI/core.py", line 163, in main
    cli.main(**kwargs)
  File ".....lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File ".....lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "...../lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "...../lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File ".....slenv/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "...../lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "...../lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "...../lib/python2.7/site-packages/SoftLayer/CLI/hardware/credentials.py", line 25, in cli
    for item in instance['operatingSystem']['passwords']:
KeyError: 'passwords'

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues

### Environment Information
Operating System:
softlayer-python version (`slcli --version`):

**Comment by allmightyspiff** [comment]
This should be fixed in the next release
