### ISSUE TITLE
slcli shell throws TypeError: prompt() got an unexpected keyword argument 'get_prompt_tokens' 

### ISSUE THREAD

**Issue by ScottieD** [softlayer/softlayer-python#988]
**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**

### Expected Behavior
`slcli shell` should run a new shell environment. 
### Actual Behavior
`slcli shell` returns python exception and traceback

### Environment Information
Operating System: Ubuntu-bionic/RHEL 7.4
softlayer-python version (`slcli --version`): slcli (SoftLayer Command-line), version 5.4.4

**Comment by allmightyspiff** [comment]
can you provide the stack trace? I'm not able to reproduce your error.

**Comment by ScottieD** [comment]
`scott@ubuntu-docker:~$ snap run slcli shell
An unexpected error has occured:
Traceback (most recent call last):
  File "/snap/slcli/129/lib/python3.5/site-packages/SoftLayer/CLI/core.py", line 182, in main
    cli.main(**kwargs)
  File "/snap/slcli/129/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/snap/slcli/129/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/snap/slcli/129/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/slcli/129/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/snap/slcli/129/lib/python3.5/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/snap/slcli/129/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/snap/slcli/129/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/snap/slcli/129/lib/python3.5/site-packages/SoftLayer/shell/core.py", line 78, in cli
    get_prompt_tokens=get_prompt_tokens,
  File "/snap/slcli/129/lib/python3.5/site-packages/prompt_toolkit/shortcuts/prompt.py", line 793, in prompt
    return session.prompt(*a, **kw)
TypeError: prompt() got an unexpected keyword argument 'get_prompt_tokens'

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues
The following snippet should be able to reproduce the error`

`[scott@5 ~]$ slcli shell
/usr/lib/python3.4/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.23) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
An unexpected error has occured:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/SoftLayer/CLI/core.py", line 176, in main
    cli.main(**kwargs)
  File "/usr/lib/python3.4/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.4/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.4/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.4/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/lib/python3.4/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib64/python3.4/site-packages/SoftLayer/shell/core.py", line 78, in cli
    get_prompt_tokens=get_prompt_tokens,
  File "/usr/lib/python3.4/site-packages/prompt_toolkit/shortcuts/prompt.py", line 793, in prompt
    return session.prompt(*a, **kw)
TypeError: prompt() got an unexpected keyword argument 'history'

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues
The following snippet should be able to reproduce the error
`

**Comment by ScottieD** [comment]
disabling some of the history functionality seems to bandaid the issue.

`        try:
            line = p_shortcuts.prompt(
                completer=complete,
                #history=history,
                auto_suggest=p_auto_suggest.AutoSuggestFromHistory(),
                #get_prompt_tokens=get_prompt_tokens,
            )`

**Comment by ScottieD** [comment]
issue resolved in pull request https://github.com/softlayer/softlayer-python/pull/993
