### ISSUE TITLE
slcli vlan detail should be graceful in handling cases when hardware/vsi have no hostname/domain attribute

### ISSUE THREAD

**Issue by flavio-fernandes** [softlayer/softlayer-python#996]
### Expected Behavior
slcli vlan detail should be more graceful in handling cases when hardware/vsi have no hostname/domain attribute

```
$ slcli vlan detail 1499927
$ echo $?
0
```

### Actual Behavior
```
    $ slcli vlan detail 1499927
    An unexpected error has occured:
    Traceback (most recent call last):
      File "/home/vagrant/.venv/local/lib/python2.7/site-packages/SoftLayer/CLI/core.py", line 176, in main
        cli.main(**kwargs)
      File "/home/vagrant/.venv/local/lib/python2.7/site-packages/click/core.py", line 697, in main
        rv = self.invoke(ctx)
      File "/home/vagrant/.venv/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/home/vagrant/.venv/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/home/vagrant/.venv/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/home/vagrant/.venv/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
        return callback(*args, **kwargs)
      File "/home/vagrant/.venv/local/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
        return ctx.invoke(f, obj, *args[1:], **kwargs)
      File "/home/vagrant/.venv/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
        return callback(*args, **kwargs)
      File "/home/vagrant/.venv/local/lib/python2.7/site-packages/SoftLayer/CLI/vlan/detail.py", line 76, in cli
        hardware['domain'],
    KeyError: 'domain'
```

### Environment Information
Operating System: Ubuntu Xenial
softlayer-python version (`slcli --version`): slcli (SoftLayer Command-line), version 5.4.4

**Comment by flavio-fernandes** [comment]
Proposed fix is in: https://github.com/softlayer/softlayer-python/pull/997
